#ifndef MIKA_EMULATORS_Z80_APPLICATIONS_PACMAN_IO_REQUEST_H
#define MIKA_EMULATORS_Z80_APPLICATIONS_PACMAN_IO_REQUEST_H

namespace emu::z80::applications::pacman {

    enum IoRequest {
        STEP_INSTRUCTION,
        STEP_CYCLE,
        CONTINUE_EXECUTION,
        TOGGLE_MUTE,
        TOGGLE_TILE_DEBUG,
        TOGGLE_SPRITE_DEBUG,
    };
}

#endif //MIKA_EMULATORS_Z80_APPLICATIONS_PACMAN_IO_REQUEST_H
