#ifndef MIKA_EMULATORS_Z80_INSTRUCTIONS_INSTRUCTIONS_H
#define MIKA_EMULATORS_Z80_INSTRUCTIONS_INSTRUCTIONS_H

#include <vector>
#include <string>
#include "z80/emulator_memory.h"
#include "z80/flags.h"
#include "z80/interrupt_mode.h"
#include "crosscutting/misc/next_byte.h"
#include "crosscutting/misc/next_word.h"
#include "crosscutting/typedefs.h"

// @formatter:off

// Main opcodes:
constexpr unsigned int NOP           = 0x00;
constexpr unsigned int LD_BC_nn      = 0x01;
constexpr unsigned int LD_MBC_A      = 0x02;
constexpr unsigned int INC_BC        = 0x03;
constexpr unsigned int INC_B         = 0x04;
constexpr unsigned int DEC_B         = 0x05;
constexpr unsigned int LD_B_n        = 0x06;
constexpr unsigned int RLCA          = 0x07;
constexpr unsigned int EX_AF_AFP     = 0x08;
constexpr unsigned int ADD_HL_BC     = 0x09;
constexpr unsigned int LD_A_MBC      = 0x0A;
constexpr unsigned int DEC_BC        = 0x0B;
constexpr unsigned int INC_C         = 0x0C;
constexpr unsigned int DEC_C         = 0x0D;
constexpr unsigned int LD_C_n        = 0x0E;
constexpr unsigned int RRCA          = 0x0F;
constexpr unsigned int DJNZ          = 0x10;
constexpr unsigned int LD_DE_nn      = 0x11;
constexpr unsigned int LD_MDE_A      = 0x12;
constexpr unsigned int INC_DE        = 0x13;
constexpr unsigned int INC_D         = 0x14;
constexpr unsigned int DEC_D         = 0x15;
constexpr unsigned int LD_D_n        = 0x16;
constexpr unsigned int RLA           = 0x17;
constexpr unsigned int JR_e          = 0x18;
constexpr unsigned int ADD_HL_DE     = 0x19;
constexpr unsigned int LD_A_MDE      = 0x1A;
constexpr unsigned int DEC_DE        = 0x1B;
constexpr unsigned int INC_E         = 0x1C;
constexpr unsigned int DEC_E         = 0x1D;
constexpr unsigned int LD_E_n        = 0x1E;
constexpr unsigned int RRA           = 0x1F;
constexpr unsigned int JR_NZ_e       = 0x20;
constexpr unsigned int LD_HL_nn      = 0x21;
constexpr unsigned int LD_Mnn_HL     = 0x22;
constexpr unsigned int INC_HL        = 0x23;
constexpr unsigned int INC_H         = 0x24;
constexpr unsigned int DEC_H         = 0x25;
constexpr unsigned int LD_H_n        = 0x26;
constexpr unsigned int DAA           = 0x27;
constexpr unsigned int JR_Z_e        = 0x28;
constexpr unsigned int ADD_HL_HL     = 0x29;
constexpr unsigned int LD_HL_Mnn     = 0x2A;
constexpr unsigned int DEC_HL        = 0x2B;
constexpr unsigned int INC_L         = 0x2C;
constexpr unsigned int DEC_L         = 0x2D;
constexpr unsigned int LD_L_n        = 0x2E;
constexpr unsigned int CPL           = 0x2F;
constexpr unsigned int JR_NC_e       = 0x30;
constexpr unsigned int LD_SP_nn      = 0x31;
constexpr unsigned int LD_Mnn_A      = 0x32;
constexpr unsigned int INC_SP        = 0x33;
constexpr unsigned int INC_MHL       = 0x34;
constexpr unsigned int DEC_MHL       = 0x35;
constexpr unsigned int LD_MHL_n      = 0x36;
constexpr unsigned int SCF           = 0x37;
constexpr unsigned int JR_C_e        = 0x38;
constexpr unsigned int ADD_HL_SP     = 0x39;
constexpr unsigned int LD_A_Mnn      = 0x3A;
constexpr unsigned int DEC_SP        = 0x3B;
constexpr unsigned int INC_A         = 0x3C;
constexpr unsigned int DEC_A         = 0x3D;
constexpr unsigned int LD_A_n        = 0x3E;
constexpr unsigned int CCF           = 0x3F;
constexpr unsigned int LD_B_B        = 0x40;
constexpr unsigned int LD_B_C        = 0x41;
constexpr unsigned int LD_B_D        = 0x42;
constexpr unsigned int LD_B_E        = 0x43;
constexpr unsigned int LD_B_H        = 0x44;
constexpr unsigned int LD_B_L        = 0x45;
constexpr unsigned int LD_B_MHL      = 0x46;
constexpr unsigned int LD_B_A        = 0x47;
constexpr unsigned int LD_C_B        = 0x48;
constexpr unsigned int LD_C_C        = 0x49;
constexpr unsigned int LD_C_D        = 0x4A;
constexpr unsigned int LD_C_E        = 0x4B;
constexpr unsigned int LD_C_H        = 0x4C;
constexpr unsigned int LD_C_L        = 0x4D;
constexpr unsigned int LD_C_MHL      = 0x4E;
constexpr unsigned int LD_C_A        = 0x4F;
constexpr unsigned int LD_D_B        = 0x50;
constexpr unsigned int LD_D_C        = 0x51;
constexpr unsigned int LD_D_D        = 0x52;
constexpr unsigned int LD_D_E        = 0x53;
constexpr unsigned int LD_D_H        = 0x54;
constexpr unsigned int LD_D_L        = 0x55;
constexpr unsigned int LD_D_MHL      = 0x56;
constexpr unsigned int LD_D_A        = 0x57;
constexpr unsigned int LD_E_B        = 0x58;
constexpr unsigned int LD_E_C        = 0x59;
constexpr unsigned int LD_E_D        = 0x5A;
constexpr unsigned int LD_E_E        = 0x5B;
constexpr unsigned int LD_E_H        = 0x5C;
constexpr unsigned int LD_E_L        = 0x5D;
constexpr unsigned int LD_E_MHL      = 0x5E;
constexpr unsigned int LD_E_A        = 0x5F;
constexpr unsigned int LD_H_B        = 0x60;
constexpr unsigned int LD_H_C        = 0x61;
constexpr unsigned int LD_H_D        = 0x62;
constexpr unsigned int LD_H_E        = 0x63;
constexpr unsigned int LD_H_H        = 0x64;
constexpr unsigned int LD_H_L        = 0x65;
constexpr unsigned int LD_H_MHL      = 0x66;
constexpr unsigned int LD_H_A        = 0x67;
constexpr unsigned int LD_L_B        = 0x68;
constexpr unsigned int LD_L_C        = 0x69;
constexpr unsigned int LD_L_D        = 0x6A;
constexpr unsigned int LD_L_E        = 0x6B;
constexpr unsigned int LD_L_H        = 0x6C;
constexpr unsigned int LD_L_L        = 0x6D;
constexpr unsigned int LD_L_MHL      = 0x6E;
constexpr unsigned int LD_L_A        = 0x6F;
constexpr unsigned int LD_MHL_B      = 0x70;
constexpr unsigned int LD_MHL_C      = 0x71;
constexpr unsigned int LD_MHL_D      = 0x72;
constexpr unsigned int LD_MHL_E      = 0x73;
constexpr unsigned int LD_MHL_H      = 0x74;
constexpr unsigned int LD_MHL_L      = 0x75;
constexpr unsigned int HALT          = 0x76;
constexpr unsigned int LD_MHL_A      = 0x77;
constexpr unsigned int LD_A_B        = 0x78;
constexpr unsigned int LD_A_C        = 0x79;
constexpr unsigned int LD_A_D        = 0x7A;
constexpr unsigned int LD_A_E        = 0x7B;
constexpr unsigned int LD_A_H        = 0x7C;
constexpr unsigned int LD_A_L        = 0x7D;
constexpr unsigned int LD_A_MHL      = 0x7E;
constexpr unsigned int LD_A_A        = 0x7F;
constexpr unsigned int ADD_A_B       = 0x80;
constexpr unsigned int ADD_A_C       = 0x81;
constexpr unsigned int ADD_A_D       = 0x82;
constexpr unsigned int ADD_A_E       = 0x83;
constexpr unsigned int ADD_A_H       = 0x84;
constexpr unsigned int ADD_A_L       = 0x85;
constexpr unsigned int ADD_A_MHL     = 0x86;
constexpr unsigned int ADD_A_A       = 0x87;
constexpr unsigned int ADC_A_B       = 0x88;
constexpr unsigned int ADC_A_C       = 0x89;
constexpr unsigned int ADC_A_D       = 0x8A;
constexpr unsigned int ADC_A_E       = 0x8B;
constexpr unsigned int ADC_A_H       = 0x8C;
constexpr unsigned int ADC_A_L       = 0x8D;
constexpr unsigned int ADC_A_MHL     = 0x8E;
constexpr unsigned int ADC_A_A       = 0x8F;
constexpr unsigned int SUB_B         = 0x90;
constexpr unsigned int SUB_C         = 0x91;
constexpr unsigned int SUB_D         = 0x92;
constexpr unsigned int SUB_E         = 0x93;
constexpr unsigned int SUB_H         = 0x94;
constexpr unsigned int SUB_L         = 0x95;
constexpr unsigned int SUB_MHL       = 0x96;
constexpr unsigned int SUB_A         = 0x97;
constexpr unsigned int SBC_A_B       = 0x98;
constexpr unsigned int SBC_A_C       = 0x99;
constexpr unsigned int SBC_A_D       = 0x9A;
constexpr unsigned int SBC_A_E       = 0x9B;
constexpr unsigned int SBC_A_H       = 0x9C;
constexpr unsigned int SBC_A_L       = 0x9D;
constexpr unsigned int SBC_A_MHL     = 0x9E;
constexpr unsigned int SBC_A_A       = 0x9F;
constexpr unsigned int AND_B         = 0xA0;
constexpr unsigned int AND_C         = 0xA1;
constexpr unsigned int AND_D         = 0xA2;
constexpr unsigned int AND_E         = 0xA3;
constexpr unsigned int AND_H         = 0xA4;
constexpr unsigned int AND_L         = 0xA5;
constexpr unsigned int AND_MHL       = 0xA6;
constexpr unsigned int AND_A         = 0xA7;
constexpr unsigned int XOR_B         = 0xA8;
constexpr unsigned int XOR_C         = 0xA9;
constexpr unsigned int XOR_D         = 0xAA;
constexpr unsigned int XOR_E         = 0xAB;
constexpr unsigned int XOR_H         = 0xAC;
constexpr unsigned int XOR_L         = 0xAD;
constexpr unsigned int XOR_MHL       = 0xAE;
constexpr unsigned int XOR_A         = 0xAF;
constexpr unsigned int OR_B          = 0xB0;
constexpr unsigned int OR_C          = 0xB1;
constexpr unsigned int OR_D          = 0xB2;
constexpr unsigned int OR_E          = 0xB3;
constexpr unsigned int OR_H          = 0xB4;
constexpr unsigned int OR_L          = 0xB5;
constexpr unsigned int OR_MHL        = 0xB6;
constexpr unsigned int OR_A          = 0xB7;
constexpr unsigned int CP_B          = 0xB8;
constexpr unsigned int CP_C          = 0xB9;
constexpr unsigned int CP_D          = 0xBA;
constexpr unsigned int CP_E          = 0xBB;
constexpr unsigned int CP_H          = 0xBC;
constexpr unsigned int CP_L          = 0xBD;
constexpr unsigned int CP_MHL        = 0xBE;
constexpr unsigned int CP_A          = 0xBF;
constexpr unsigned int RET_NZ        = 0xC0;
constexpr unsigned int POP_BC        = 0xC1;
constexpr unsigned int JP_NZ         = 0xC2;
constexpr unsigned int JP            = 0xC3;
constexpr unsigned int CALL_NZ       = 0xC4;
constexpr unsigned int PUSH_BC       = 0xC5;
constexpr unsigned int ADD_A_n       = 0xC6;
constexpr unsigned int RST_0         = 0xC7;
constexpr unsigned int RET_Z         = 0xC8;
constexpr unsigned int RET           = 0xC9;
constexpr unsigned int JP_Z          = 0xCA;
constexpr unsigned int BITS          = 0xCB;
constexpr unsigned int CALL_Z        = 0xCC;
constexpr unsigned int CALL          = 0xCD;
constexpr unsigned int ADC_A_n       = 0xCE;
constexpr unsigned int RST_1         = 0xCF;
constexpr unsigned int RET_NC        = 0xD0;
constexpr unsigned int POP_DE        = 0xD1;
constexpr unsigned int JP_NC         = 0xD2;
constexpr unsigned int OUT           = 0xD3;
constexpr unsigned int CALL_NC       = 0xD4;
constexpr unsigned int PUSH_DE       = 0xD5;
constexpr unsigned int SUB_n         = 0xD6;
constexpr unsigned int RST_2         = 0xD7;
constexpr unsigned int RET_C         = 0xD8;
constexpr unsigned int EXX           = 0xD9;
constexpr unsigned int JP_C          = 0xDA;
constexpr unsigned int IN            = 0xDB;
constexpr unsigned int CALL_C        = 0xDC;
constexpr unsigned int IX            = 0xDD;
constexpr unsigned int SBC_A_n       = 0xDE;
constexpr unsigned int RST_3         = 0xDF;
constexpr unsigned int RET_PO        = 0xE0;
constexpr unsigned int POP_HL        = 0xE1;
constexpr unsigned int JP_PO         = 0xE2;
constexpr unsigned int EX_MSP_HL     = 0xE3;
constexpr unsigned int CALL_PO       = 0xE4;
constexpr unsigned int PUSH_HL       = 0xE5;
constexpr unsigned int AND_n         = 0xE6;
constexpr unsigned int RST_4         = 0xE7;
constexpr unsigned int RET_PE        = 0xE8;
constexpr unsigned int JP_MHL        = 0xE9;
constexpr unsigned int JP_PE         = 0xEA;
constexpr unsigned int EX_DE_HL      = 0xEB;
constexpr unsigned int CALL_PE       = 0xEC;
constexpr unsigned int EXTD          = 0xED;
constexpr unsigned int XOR_n         = 0xEE;
constexpr unsigned int RST_5         = 0xEF;
constexpr unsigned int RET_P         = 0xF0;
constexpr unsigned int POP_AF        = 0xF1;
constexpr unsigned int JP_P          = 0xF2;
constexpr unsigned int DI            = 0xF3;
constexpr unsigned int CALL_P        = 0xF4;
constexpr unsigned int PUSH_AF       = 0xF5;
constexpr unsigned int OR_n          = 0xF6;
constexpr unsigned int RST_6         = 0xF7;
constexpr unsigned int RET_M         = 0xF8;
constexpr unsigned int LD_SP_HL      = 0xF9;
constexpr unsigned int JP_M          = 0xFA;
constexpr unsigned int EI            = 0xFB;
constexpr unsigned int CALL_M        = 0xFC;
constexpr unsigned int IY            = 0xFD;
constexpr unsigned int CP_n          = 0xFE;
constexpr unsigned int RST_7         = 0xFF;

// BITS opcodes:
constexpr unsigned int RLC_B         = 0x00;
constexpr unsigned int RLC_C         = 0x01;
constexpr unsigned int RLC_D         = 0x02;
constexpr unsigned int RLC_E         = 0x03;
constexpr unsigned int RLC_H         = 0x04;
constexpr unsigned int RLC_L         = 0x05;
constexpr unsigned int RLC_MHL       = 0x06;
constexpr unsigned int RLC_A         = 0x07;
constexpr unsigned int RRC_B         = 0x08;
constexpr unsigned int RRC_C         = 0x09;
constexpr unsigned int RRC_D         = 0x0A;
constexpr unsigned int RRC_E         = 0x0B;
constexpr unsigned int RRC_H         = 0x0C;
constexpr unsigned int RRC_L         = 0x0D;
constexpr unsigned int RRC_MHL       = 0x0E;
constexpr unsigned int RRC_A         = 0x0F;
constexpr unsigned int RL_B          = 0x10;
constexpr unsigned int RL_C          = 0x11;
constexpr unsigned int RL_D          = 0x12;
constexpr unsigned int RL_E          = 0x13;
constexpr unsigned int RL_H          = 0x14;
constexpr unsigned int RL_L          = 0x15;
constexpr unsigned int RL_MHL        = 0x16;
constexpr unsigned int RL_A          = 0x17;
constexpr unsigned int RR_B          = 0x18;
constexpr unsigned int RR_C          = 0x19;
constexpr unsigned int RR_D          = 0x1A;
constexpr unsigned int RR_E          = 0x1B;
constexpr unsigned int RR_H          = 0x1C;
constexpr unsigned int RR_L          = 0x1D;
constexpr unsigned int RR_MHL        = 0x1E;
constexpr unsigned int RR_A          = 0x1F;
constexpr unsigned int SLA_B         = 0x20;
constexpr unsigned int SLA_C         = 0x21;
constexpr unsigned int SLA_D         = 0x22;
constexpr unsigned int SLA_E         = 0x23;
constexpr unsigned int SLA_H         = 0x24;
constexpr unsigned int SLA_L         = 0x25;
constexpr unsigned int SLA_MHL       = 0x26;
constexpr unsigned int SLA_A         = 0x27;
constexpr unsigned int SRA_B         = 0x28;
constexpr unsigned int SRA_C         = 0x29;
constexpr unsigned int SRA_D         = 0x2A;
constexpr unsigned int SRA_E         = 0x2B;
constexpr unsigned int SRA_H         = 0x2C;
constexpr unsigned int SRA_L         = 0x2D;
constexpr unsigned int SRA_MHL       = 0x2E;
constexpr unsigned int SRA_A         = 0x2F;
constexpr unsigned int SLL_B         = 0x30;
constexpr unsigned int SLL_C         = 0x31;
constexpr unsigned int SLL_D         = 0x32;
constexpr unsigned int SLL_E         = 0x33;
constexpr unsigned int SLL_H         = 0x34;
constexpr unsigned int SLL_L         = 0x35;
constexpr unsigned int SLL_MHL       = 0x36;
constexpr unsigned int SLL_A         = 0x37;
constexpr unsigned int SRL_B         = 0x38;
constexpr unsigned int SRL_C         = 0x39;
constexpr unsigned int SRL_D         = 0x3A;
constexpr unsigned int SRL_E         = 0x3B;
constexpr unsigned int SRL_H         = 0x3C;
constexpr unsigned int SRL_L         = 0x3D;
constexpr unsigned int SRL_MHL       = 0x3E;
constexpr unsigned int SRL_A         = 0x3F;
constexpr unsigned int BIT_0_B       = 0x40;
constexpr unsigned int BIT_0_C       = 0x41;
constexpr unsigned int BIT_0_D       = 0x42;
constexpr unsigned int BIT_0_E       = 0x43;
constexpr unsigned int BIT_0_H       = 0x44;
constexpr unsigned int BIT_0_L       = 0x45;
constexpr unsigned int BIT_0_MHL     = 0x46;
constexpr unsigned int BIT_0_A       = 0x47;
constexpr unsigned int BIT_1_B       = 0x48;
constexpr unsigned int BIT_1_C       = 0x49;
constexpr unsigned int BIT_1_D       = 0x4A;
constexpr unsigned int BIT_1_E       = 0x4B;
constexpr unsigned int BIT_1_H       = 0x4C;
constexpr unsigned int BIT_1_L       = 0x4D;
constexpr unsigned int BIT_1_MHL     = 0x4E;
constexpr unsigned int BIT_1_A       = 0x4F;
constexpr unsigned int BIT_2_B       = 0x50;
constexpr unsigned int BIT_2_C       = 0x51;
constexpr unsigned int BIT_2_D       = 0x52;
constexpr unsigned int BIT_2_E       = 0x53;
constexpr unsigned int BIT_2_H       = 0x54;
constexpr unsigned int BIT_2_L       = 0x55;
constexpr unsigned int BIT_2_MHL     = 0x56;
constexpr unsigned int BIT_2_A       = 0x57;
constexpr unsigned int BIT_3_B       = 0x58;
constexpr unsigned int BIT_3_C       = 0x59;
constexpr unsigned int BIT_3_D       = 0x5A;
constexpr unsigned int BIT_3_E       = 0x5B;
constexpr unsigned int BIT_3_H       = 0x5C;
constexpr unsigned int BIT_3_L       = 0x5D;
constexpr unsigned int BIT_3_MHL     = 0x5E;
constexpr unsigned int BIT_3_A       = 0x5F;
constexpr unsigned int BIT_4_B       = 0x60;
constexpr unsigned int BIT_4_C       = 0x61;
constexpr unsigned int BIT_4_D       = 0x62;
constexpr unsigned int BIT_4_E       = 0x63;
constexpr unsigned int BIT_4_H       = 0x64;
constexpr unsigned int BIT_4_L       = 0x65;
constexpr unsigned int BIT_4_MHL     = 0x66;
constexpr unsigned int BIT_4_A       = 0x67;
constexpr unsigned int BIT_5_B       = 0x68;
constexpr unsigned int BIT_5_C       = 0x69;
constexpr unsigned int BIT_5_D       = 0x6A;
constexpr unsigned int BIT_5_E       = 0x6B;
constexpr unsigned int BIT_5_H       = 0x6C;
constexpr unsigned int BIT_5_L       = 0x6D;
constexpr unsigned int BIT_5_MHL     = 0x6E;
constexpr unsigned int BIT_5_A       = 0x6F;
constexpr unsigned int BIT_6_B       = 0x70;
constexpr unsigned int BIT_6_C       = 0x71;
constexpr unsigned int BIT_6_D       = 0x72;
constexpr unsigned int BIT_6_E       = 0x73;
constexpr unsigned int BIT_6_H       = 0x74;
constexpr unsigned int BIT_6_L       = 0x75;
constexpr unsigned int BIT_6_MHL     = 0x76;
constexpr unsigned int BIT_6_A       = 0x77;
constexpr unsigned int BIT_7_B       = 0x78;
constexpr unsigned int BIT_7_C       = 0x79;
constexpr unsigned int BIT_7_D       = 0x7A;
constexpr unsigned int BIT_7_E       = 0x7B;
constexpr unsigned int BIT_7_H       = 0x7C;
constexpr unsigned int BIT_7_L       = 0x7D;
constexpr unsigned int BIT_7_MHL     = 0x7E;
constexpr unsigned int BIT_7_A       = 0x7F;
constexpr unsigned int RES_0_B       = 0x80;
constexpr unsigned int RES_0_C       = 0x81;
constexpr unsigned int RES_0_D       = 0x82;
constexpr unsigned int RES_0_E       = 0x83;
constexpr unsigned int RES_0_H       = 0x84;
constexpr unsigned int RES_0_L       = 0x85;
constexpr unsigned int RES_0_MHL     = 0x86;
constexpr unsigned int RES_0_A       = 0x87;
constexpr unsigned int RES_1_B       = 0x88;
constexpr unsigned int RES_1_C       = 0x89;
constexpr unsigned int RES_1_D       = 0x8A;
constexpr unsigned int RES_1_E       = 0x8B;
constexpr unsigned int RES_1_H       = 0x8C;
constexpr unsigned int RES_1_L       = 0x8D;
constexpr unsigned int RES_1_MHL     = 0x8E;
constexpr unsigned int RES_1_A       = 0x8F;
constexpr unsigned int RES_2_B       = 0x90;
constexpr unsigned int RES_2_C       = 0x91;
constexpr unsigned int RES_2_D       = 0x92;
constexpr unsigned int RES_2_E       = 0x93;
constexpr unsigned int RES_2_H       = 0x94;
constexpr unsigned int RES_2_L       = 0x95;
constexpr unsigned int RES_2_MHL     = 0x96;
constexpr unsigned int RES_2_A       = 0x97;
constexpr unsigned int RES_3_B       = 0x98;
constexpr unsigned int RES_3_C       = 0x99;
constexpr unsigned int RES_3_D       = 0x9A;
constexpr unsigned int RES_3_E       = 0x9B;
constexpr unsigned int RES_3_H       = 0x9C;
constexpr unsigned int RES_3_L       = 0x9D;
constexpr unsigned int RES_3_MHL     = 0x9E;
constexpr unsigned int RES_3_A       = 0x9F;
constexpr unsigned int RES_4_B       = 0xA0;
constexpr unsigned int RES_4_C       = 0xA1;
constexpr unsigned int RES_4_D       = 0xA2;
constexpr unsigned int RES_4_E       = 0xA3;
constexpr unsigned int RES_4_H       = 0xA4;
constexpr unsigned int RES_4_L       = 0xA5;
constexpr unsigned int RES_4_MHL     = 0xA6;
constexpr unsigned int RES_4_A       = 0xA7;
constexpr unsigned int RES_5_B       = 0xA8;
constexpr unsigned int RES_5_C       = 0xA9;
constexpr unsigned int RES_5_D       = 0xAA;
constexpr unsigned int RES_5_E       = 0xAB;
constexpr unsigned int RES_5_H       = 0xAC;
constexpr unsigned int RES_5_L       = 0xAD;
constexpr unsigned int RES_5_MHL     = 0xAE;
constexpr unsigned int RES_5_A       = 0xAF;
constexpr unsigned int RES_6_B       = 0xB0;
constexpr unsigned int RES_6_C       = 0xB1;
constexpr unsigned int RES_6_D       = 0xB2;
constexpr unsigned int RES_6_E       = 0xB3;
constexpr unsigned int RES_6_H       = 0xB4;
constexpr unsigned int RES_6_L       = 0xB5;
constexpr unsigned int RES_6_MHL     = 0xB6;
constexpr unsigned int RES_6_A       = 0xB7;
constexpr unsigned int RES_7_B       = 0xB8;
constexpr unsigned int RES_7_C       = 0xB9;
constexpr unsigned int RES_7_D       = 0xBA;
constexpr unsigned int RES_7_E       = 0xBB;
constexpr unsigned int RES_7_H       = 0xBC;
constexpr unsigned int RES_7_L       = 0xBD;
constexpr unsigned int RES_7_MHL     = 0xBE;
constexpr unsigned int RES_7_A       = 0xBF;
constexpr unsigned int SET_0_B       = 0xC0;
constexpr unsigned int SET_0_C       = 0xC1;
constexpr unsigned int SET_0_D       = 0xC2;
constexpr unsigned int SET_0_E       = 0xC3;
constexpr unsigned int SET_0_H       = 0xC4;
constexpr unsigned int SET_0_L       = 0xC5;
constexpr unsigned int SET_0_MHL     = 0xC6;
constexpr unsigned int SET_0_A       = 0xC7;
constexpr unsigned int SET_1_B       = 0xC8;
constexpr unsigned int SET_1_C       = 0xC9;
constexpr unsigned int SET_1_D       = 0xCA;
constexpr unsigned int SET_1_E       = 0xCB;
constexpr unsigned int SET_1_H       = 0xCC;
constexpr unsigned int SET_1_L       = 0xCD;
constexpr unsigned int SET_1_MHL     = 0xCE;
constexpr unsigned int SET_1_A       = 0xCF;
constexpr unsigned int SET_2_B       = 0xD0;
constexpr unsigned int SET_2_C       = 0xD1;
constexpr unsigned int SET_2_D       = 0xD2;
constexpr unsigned int SET_2_E       = 0xD3;
constexpr unsigned int SET_2_H       = 0xD4;
constexpr unsigned int SET_2_L       = 0xD5;
constexpr unsigned int SET_2_MHL     = 0xD6;
constexpr unsigned int SET_2_A       = 0xD7;
constexpr unsigned int SET_3_B       = 0xD8;
constexpr unsigned int SET_3_C       = 0xD9;
constexpr unsigned int SET_3_D       = 0xDA;
constexpr unsigned int SET_3_E       = 0xDB;
constexpr unsigned int SET_3_H       = 0xDC;
constexpr unsigned int SET_3_L       = 0xDD;
constexpr unsigned int SET_3_MHL     = 0xDE;
constexpr unsigned int SET_3_A       = 0xDF;
constexpr unsigned int SET_4_B       = 0xE0;
constexpr unsigned int SET_4_C       = 0xE1;
constexpr unsigned int SET_4_D       = 0xE2;
constexpr unsigned int SET_4_E       = 0xE3;
constexpr unsigned int SET_4_H       = 0xE4;
constexpr unsigned int SET_4_L       = 0xE5;
constexpr unsigned int SET_4_MHL     = 0xE6;
constexpr unsigned int SET_4_A       = 0xE7;
constexpr unsigned int SET_5_B       = 0xE8;
constexpr unsigned int SET_5_C       = 0xE9;
constexpr unsigned int SET_5_D       = 0xEA;
constexpr unsigned int SET_5_E       = 0xEB;
constexpr unsigned int SET_5_H       = 0xEC;
constexpr unsigned int SET_5_L       = 0xED;
constexpr unsigned int SET_5_MHL     = 0xEE;
constexpr unsigned int SET_5_A       = 0xEF;
constexpr unsigned int SET_6_B       = 0xF0;
constexpr unsigned int SET_6_C       = 0xF1;
constexpr unsigned int SET_6_D       = 0xF2;
constexpr unsigned int SET_6_E       = 0xF3;
constexpr unsigned int SET_6_H       = 0xF4;
constexpr unsigned int SET_6_L       = 0xF5;
constexpr unsigned int SET_6_MHL     = 0xF6;
constexpr unsigned int SET_6_A       = 0xF7;
constexpr unsigned int SET_7_B       = 0xF8;
constexpr unsigned int SET_7_C       = 0xF9;
constexpr unsigned int SET_7_D       = 0xFA;
constexpr unsigned int SET_7_E       = 0xFB;
constexpr unsigned int SET_7_H       = 0xFC;
constexpr unsigned int SET_7_L       = 0xFD;
constexpr unsigned int SET_7_MHL     = 0xFE;
constexpr unsigned int SET_7_A       = 0xFF;

// IX/IY opcodes:
constexpr unsigned int INC_B_UNDOC         = 0x04;
constexpr unsigned int DEC_B_UNDOC         = 0x05;
constexpr unsigned int LD_B_n_UNDOC        = 0x06;
constexpr unsigned int ADD_IXY_BC          = 0x09;
constexpr unsigned int INC_C_UNDOC         = 0x0C;
constexpr unsigned int DEC_C_UNDOC         = 0x0D;
constexpr unsigned int LD_C_n_UNDOC        = 0x0E;
constexpr unsigned int INC_D_UNDOC         = 0x14;
constexpr unsigned int DEC_D_UNDOC         = 0x15;
constexpr unsigned int LD_D_n_UNDOC        = 0x16;
constexpr unsigned int ADD_IXY_DE          = 0x19;
constexpr unsigned int INC_E_UNDOC         = 0x1C;
constexpr unsigned int DEC_E_UNDOC         = 0x1D;
constexpr unsigned int LD_E_n_UNDOC        = 0x1E;
constexpr unsigned int LD_IXY_nn           = 0x21;
constexpr unsigned int LD_Mnn_IXY          = 0x22;
constexpr unsigned int INC_IXY             = 0x23;
constexpr unsigned int INC_IXH_UNDOC       = 0x24;
constexpr unsigned int DEC_IXH_UNDOC       = 0x25;
constexpr unsigned int LD_IXYH_n_UNDOC     = 0x26;
constexpr unsigned int ADD_IXY_IXY         = 0x29;
constexpr unsigned int LD_IXY_Mnn          = 0x2A;
constexpr unsigned int DEC_IXY             = 0x2B;
constexpr unsigned int INC_IXL_UNDOC       = 0x2C;
constexpr unsigned int DEC_IXL_UNDOC       = 0x2D;
constexpr unsigned int LD_IXYL_n_UNDOC     = 0x2E;
constexpr unsigned int INC_MIXY_P_n        = 0x34;
constexpr unsigned int DEC_MIXY_P_n        = 0x35;
constexpr unsigned int LD_MIXY_P_n_d       = 0x36;
constexpr unsigned int ADD_IXY_SP          = 0x39;
constexpr unsigned int INC_A_UNDOC         = 0x3C;
constexpr unsigned int DEC_A_UNDOC         = 0x3D;
constexpr unsigned int LD_A_n_UNDOC        = 0x3E;
constexpr unsigned int LD_B_B_UNDOC        = 0x40;
constexpr unsigned int LD_B_C_UNDOC        = 0x41;
constexpr unsigned int LD_B_D_UNDOC        = 0x42;
constexpr unsigned int LD_B_E_UNDOC        = 0x43;
constexpr unsigned int LD_B_IXYH_UNDOC     = 0x44;
constexpr unsigned int LD_B_IXYL_UNDOC     = 0x45;
constexpr unsigned int LD_B_MIXY_P_n       = 0x46;
constexpr unsigned int LD_B_A_UNDOC        = 0x47;
constexpr unsigned int LD_C_B_UNDOC        = 0x48;
constexpr unsigned int LD_C_C_UNDOC        = 0x49;
constexpr unsigned int LD_C_D_UNDOC        = 0x4A;
constexpr unsigned int LD_C_E_UNDOC        = 0x4B;
constexpr unsigned int LD_C_IXYH_UNDOC     = 0x4C;
constexpr unsigned int LD_C_IXYL_UNDOC     = 0x4D;
constexpr unsigned int LD_C_MIXY_P_n       = 0x4E;
constexpr unsigned int LD_C_A_UNDOC        = 0x4F;
constexpr unsigned int LD_D_B_UNDOC        = 0x50;
constexpr unsigned int LD_D_C_UNDOC        = 0x51;
constexpr unsigned int LD_D_D_UNDOC        = 0x52;
constexpr unsigned int LD_D_E_UNDOC        = 0x53;
constexpr unsigned int LD_D_IXYH_UNDOC     = 0x54;
constexpr unsigned int LD_D_IXYL_UNDOC     = 0x55;
constexpr unsigned int LD_D_MIXY_P_n       = 0x56;
constexpr unsigned int LD_D_A_UNDOC        = 0x57;
constexpr unsigned int LD_E_B_UNDOC        = 0x58;
constexpr unsigned int LD_E_C_UNDOC        = 0x59;
constexpr unsigned int LD_E_D_UNDOC        = 0x5A;
constexpr unsigned int LD_E_E_UNDOC        = 0x5B;
constexpr unsigned int LD_E_IXYH_UNDOC     = 0x5C;
constexpr unsigned int LD_E_IXYL_UNDOC     = 0x5D;
constexpr unsigned int LD_E_MIXY_P_n       = 0x5E;
constexpr unsigned int LD_E_A_UNDOC        = 0x5F;
constexpr unsigned int LD_IXYH_B_UNDOC     = 0x60;
constexpr unsigned int LD_IXYH_C_UNDOC     = 0x61;
constexpr unsigned int LD_IXYH_D_UNDOC     = 0x62;
constexpr unsigned int LD_IXYH_E_UNDOC     = 0x63;
constexpr unsigned int LD_IXYH_IXYH_UNDOC  = 0x64;
constexpr unsigned int LD_IXYH_IXYL_UNDOC  = 0x65;
constexpr unsigned int LD_H_MIXY_P_n       = 0x66;
constexpr unsigned int LD_IXYH_A_UNDOC     = 0x67;
constexpr unsigned int LD_IXYL_B_UNDOC     = 0x68;
constexpr unsigned int LD_IXYL_C_UNDOC     = 0x69;
constexpr unsigned int LD_IXYL_D_UNDOC     = 0x6A;
constexpr unsigned int LD_IXYL_E_UNDOC     = 0x6B;
constexpr unsigned int LD_IXYL_IXYH_UNDOC  = 0x6C;
constexpr unsigned int LD_IXYL_IXYL_UNDOC  = 0x6D;
constexpr unsigned int LD_L_MIXY_P_n       = 0x6E;
constexpr unsigned int LD_IXYL_A_UNDOC     = 0x6F;
constexpr unsigned int LD_MIXY_P_n_B       = 0x70;
constexpr unsigned int LD_MIXY_P_n_C       = 0x71;
constexpr unsigned int LD_MIXY_P_n_D       = 0x72;
constexpr unsigned int LD_MIXY_P_n_E       = 0x73;
constexpr unsigned int LD_MIXY_P_n_H       = 0x74;
constexpr unsigned int LD_MIXY_P_n_L       = 0x75;
constexpr unsigned int LD_MIXY_P_n_A       = 0x77;
constexpr unsigned int LD_A_B_UNDOC        = 0x78;
constexpr unsigned int LD_A_C_UNDOC        = 0x79;
constexpr unsigned int LD_A_D_UNDOC        = 0x7A;
constexpr unsigned int LD_A_E_UNDOC        = 0x7B;
constexpr unsigned int LD_A_IXYH_UNDOC     = 0x7C;
constexpr unsigned int LD_A_IXYL_UNDOC     = 0x7D;
constexpr unsigned int LD_A_MIXY_P_n       = 0x7E;
constexpr unsigned int LD_A_A_UNDOC        = 0x7F;
constexpr unsigned int ADD_A_B_UNDOC       = 0x80;
constexpr unsigned int ADD_A_C_UNDOC       = 0x81;
constexpr unsigned int ADD_A_D_UNDOC       = 0x82;
constexpr unsigned int ADD_A_E_UNDOC       = 0x83;
constexpr unsigned int ADD_A_IXYH_UNDOC    = 0x84;
constexpr unsigned int ADD_A_IXYL_UNDOC    = 0x85;
constexpr unsigned int ADD_A_MIXY_P_n      = 0x86;
constexpr unsigned int ADD_A_A_UNDOC       = 0x87;
constexpr unsigned int ADC_A_B_UNDOC       = 0x88;
constexpr unsigned int ADC_A_C_UNDOC       = 0x89;
constexpr unsigned int ADC_A_D_UNDOC       = 0x8A;
constexpr unsigned int ADC_A_E_UNDOC       = 0x8B;
constexpr unsigned int ADC_A_IXYH_UNDOC    = 0x8C;
constexpr unsigned int ADC_A_IXYL_UNDOC    = 0x8D;
constexpr unsigned int ADC_A_MIXY_P_n      = 0x8E;
constexpr unsigned int ADC_A_A_UNDOC       = 0x8F;
constexpr unsigned int SUB_B_UNDOC         = 0x90;
constexpr unsigned int SUB_C_UNDOC         = 0x91;
constexpr unsigned int SUB_D_UNDOC         = 0x92;
constexpr unsigned int SUB_E_UNDOC         = 0x93;
constexpr unsigned int SUB_IXYH_UNDOC      = 0x94;
constexpr unsigned int SUB_IXYL_UNDOC      = 0x95;
constexpr unsigned int SUB_MIXY_P_n        = 0x96;
constexpr unsigned int SUB_A_UNDOC         = 0x97;
constexpr unsigned int SBC_A_B_UNDOC       = 0x98;
constexpr unsigned int SBC_A_C_UNDOC       = 0x99;
constexpr unsigned int SBC_A_D_UNDOC       = 0x9A;
constexpr unsigned int SBC_A_E_UNDOC       = 0x9B;
constexpr unsigned int SBC_A_IXYH_UNDOC    = 0x9C;
constexpr unsigned int SBC_A_IXYL_UNDOC    = 0x9D;
constexpr unsigned int SBC_A_MIXY_P_n      = 0x9E;
constexpr unsigned int SBC_A_A_UNDOC       = 0x9F;
constexpr unsigned int AND_B_UNDOC         = 0xA0;
constexpr unsigned int AND_C_UNDOC         = 0xA1;
constexpr unsigned int AND_D_UNDOC         = 0xA2;
constexpr unsigned int AND_E_UNDOC         = 0xA3;
constexpr unsigned int AND_IXYH_UNDOC      = 0xA4;
constexpr unsigned int AND_IXYL_UNDOC      = 0xA5;
constexpr unsigned int AND_MIXY_P_n        = 0xA6;
constexpr unsigned int AND_A_UNDOC         = 0xA7;
constexpr unsigned int XOR_B_UNDOC         = 0xA8;
constexpr unsigned int XOR_C_UNDOC         = 0xA9;
constexpr unsigned int XOR_D_UNDOC         = 0xAA;
constexpr unsigned int XOR_E_UNDOC         = 0xAB;
constexpr unsigned int XOR_IXYH_UNDOC      = 0xAC;
constexpr unsigned int XOR_IXYL_UNDOC      = 0xAD;
constexpr unsigned int XOR_MIXY_P_n        = 0xAE;
constexpr unsigned int XOR_A_UNDOC         = 0xAF;
constexpr unsigned int OR_B_UNDOC          = 0xB0;
constexpr unsigned int OR_C_UNDOC          = 0xB1;
constexpr unsigned int OR_D_UNDOC          = 0xB2;
constexpr unsigned int OR_E_UNDOC          = 0xB3;
constexpr unsigned int OR_IXYH_UNDOC       = 0xB4;
constexpr unsigned int OR_IXYL_UNDOC       = 0xB5;
constexpr unsigned int OR_MIXY_P_n         = 0xB6;
constexpr unsigned int OR_A_UNDOC          = 0xB7;
constexpr unsigned int CP_B_UNDOC          = 0xB8;
constexpr unsigned int CP_C_UNDOC          = 0xB9;
constexpr unsigned int CP_D_UNDOC          = 0xBA;
constexpr unsigned int CP_E_UNDOC          = 0xBB;
constexpr unsigned int CP_IXYH_UNDOC       = 0xBC;
constexpr unsigned int CP_IXYL_UNDOC       = 0xBD;
constexpr unsigned int CP_MIXY_P_n         = 0xBE;
constexpr unsigned int CP_A_UNDOC          = 0xBF;
constexpr unsigned int IXY_BITS            = 0xCB;
constexpr unsigned int POP_IXY             = 0xE1;
constexpr unsigned int EX_MSP_IX           = 0xE3;
constexpr unsigned int PUSH_IXY            = 0xE5;
constexpr unsigned int JP_MIXY             = 0xE9;
constexpr unsigned int LD_SP_IXY           = 0xF9;

// IXY BITS opcodes
constexpr unsigned int RLC_MIXY_P_n_B_UNDOC1 = 0x00;
constexpr unsigned int RLC_MIXY_P_n_C_UNDOC1 = 0x01;
constexpr unsigned int RLC_MIXY_P_n_D_UNDOC1 = 0x02;
constexpr unsigned int RLC_MIXY_P_n_E_UNDOC1 = 0x03;
constexpr unsigned int RLC_MIXY_P_n_H_UNDOC1 = 0x04;
constexpr unsigned int RLC_MIXY_P_n_L_UNDOC1 = 0x05;
constexpr unsigned int RLC_MIXY_P_n          = 0x06;
constexpr unsigned int RLC_MIXY_P_n_A_UNDOC1 = 0x07;
constexpr unsigned int RL_MIXY_P_n_B_UNDOC1  = 0x10;
constexpr unsigned int RRC_MIXY_P_n          = 0x0E;
constexpr unsigned int RL_MIXY_P_n           = 0x16;
constexpr unsigned int RR_MIXY_P_n           = 0x1E;
constexpr unsigned int SLA_MIXY_P_n          = 0x26;
constexpr unsigned int SRA_MIXY_P_n          = 0x2E;
constexpr unsigned int SLL_MIXY_P_n          = 0x36;
constexpr unsigned int SRL_MIXY_P_n          = 0x3E;
constexpr unsigned int BIT_0_MIXY_P_n        = 0x46;
constexpr unsigned int BIT_1_MIXY_P_n        = 0x4E;
constexpr unsigned int BIT_2_MIXY_P_n        = 0x56;
constexpr unsigned int BIT_3_MIXY_P_n        = 0x5E;
constexpr unsigned int BIT_4_MIXY_P_n        = 0x66;
constexpr unsigned int BIT_5_MIXY_P_n        = 0x6E;
constexpr unsigned int BIT_6_MIXY_P_n        = 0x76;
constexpr unsigned int BIT_7_MIXY_P_n        = 0x7E;
constexpr unsigned int RES_0_MIXY_P_n        = 0x86;
constexpr unsigned int RES_1_MIXY_P_n        = 0x8E;
constexpr unsigned int RES_2_MIXY_P_n        = 0x96;
constexpr unsigned int RES_3_MIXY_P_n        = 0x9E;
constexpr unsigned int RES_4_MIXY_P_n        = 0xA6;
constexpr unsigned int RES_5_MIXY_P_n        = 0xAE;
constexpr unsigned int RES_6_MIXY_P_n        = 0xB6;
constexpr unsigned int RES_7_MIXY_P_n        = 0xBE;
constexpr unsigned int SET_0_MIXY_P_n        = 0xC6;
constexpr unsigned int SET_1_MIXY_P_n        = 0xCE;
constexpr unsigned int SET_2_MIXY_P_n        = 0xD6;
constexpr unsigned int SET_3_MIXY_P_n        = 0xDE;
constexpr unsigned int SET_4_MIXY_P_n        = 0xE6;
constexpr unsigned int SET_5_MIXY_P_n        = 0xEE;
constexpr unsigned int SET_6_MIXY_P_n        = 0xF6;
constexpr unsigned int SET_7_MIXY_P_n        = 0xFE;

// EXTD opcodes:
constexpr unsigned int IN_B_MC         = 0x40;
constexpr unsigned int OUT_MC_B        = 0x41;
constexpr unsigned int SBC_HL_BC       = 0x42;
constexpr unsigned int LD_Mnn_BC       = 0x43;
constexpr unsigned int NEG             = 0x44;
constexpr unsigned int RETN            = 0x45;
constexpr unsigned int IM_0_1          = 0x46;
constexpr unsigned int LD_I_A          = 0x47;
constexpr unsigned int IN_C_MC         = 0x48;
constexpr unsigned int OUT_MC_C        = 0x49;
constexpr unsigned int ADC_HL_BC       = 0x4A;
constexpr unsigned int LD_BC_Mnn       = 0x4B;
constexpr unsigned int NEG_UNDOC1      = 0x4C;
constexpr unsigned int RETI            = 0x4D;
constexpr unsigned int LD_R_A          = 0x4F;
constexpr unsigned int IN_D_MC         = 0x50;
constexpr unsigned int OUT_MC_D        = 0x51;
constexpr unsigned int SBC_HL_DE       = 0x52;
constexpr unsigned int LD_Mnn_DE       = 0x53;
constexpr unsigned int NEG_UNDOC2      = 0x54;
constexpr unsigned int IM_1_1          = 0x56;
constexpr unsigned int LD_A_I          = 0x57;
constexpr unsigned int IN_E_MC         = 0x58;
constexpr unsigned int OUT_MC_E        = 0x59;
constexpr unsigned int ADC_HL_DE       = 0x5A;
constexpr unsigned int LD_DE_Mnn       = 0x5B;
constexpr unsigned int NEG_UNDOC3      = 0x5C;
constexpr unsigned int IM_2            = 0x5E;
constexpr unsigned int LD_A_R          = 0x5F;
constexpr unsigned int IN_H_MC         = 0x60;
constexpr unsigned int OUT_MC_H        = 0x61;
constexpr unsigned int SBC_HL_HL       = 0x62;
constexpr unsigned int LD_Mnn_HL_UNDOC = 0x63;
constexpr unsigned int NEG_UNDOC4      = 0x64;
constexpr unsigned int IM_0_2          = 0x66;
constexpr unsigned int RRD             = 0x67;
constexpr unsigned int IN_L_MC         = 0x68;
constexpr unsigned int OUT_MC_L        = 0x69;
constexpr unsigned int ADC_HL_HL       = 0x6A;
constexpr unsigned int LD_HL_Mnn_UNDOC = 0x6B;
constexpr unsigned int NEG_UNDOC5      = 0x6C;
constexpr unsigned int RLD             = 0x6F;
constexpr unsigned int IN_MC           = 0x70;
constexpr unsigned int OUT_MC_0        = 0x71;
constexpr unsigned int SBC_HL_SP       = 0x72;
constexpr unsigned int LD_Mnn_SP       = 0x73;
constexpr unsigned int NEG_UNDOC6      = 0x74;
constexpr unsigned int IM_1_2          = 0x76;
constexpr unsigned int IN_A_MC         = 0x78;
constexpr unsigned int OUT_MC_A        = 0x79;
constexpr unsigned int ADC_HL_SP       = 0x7A;
constexpr unsigned int LD_SP_Mnn       = 0x7B;
constexpr unsigned int NEG_UNDOC7      = 0x7C;
constexpr unsigned int LDI             = 0xA0;
constexpr unsigned int CPI             = 0xA1;
constexpr unsigned int INI             = 0xA2;
constexpr unsigned int OUTI            = 0xA3;
constexpr unsigned int LDD             = 0xA8;
constexpr unsigned int CPD             = 0xA9;
constexpr unsigned int IND             = 0xAA;
constexpr unsigned int OUTD            = 0xAB;
constexpr unsigned int LDIR            = 0xB0;
constexpr unsigned int CPIR            = 0xB1;
constexpr unsigned int INIR            = 0xB2;
constexpr unsigned int OTIR            = 0xB3;
constexpr unsigned int LDDR            = 0xB8;
constexpr unsigned int CPDR            = 0xB9;
constexpr unsigned int INDR            = 0xBA;
constexpr unsigned int OTDR            = 0xBB;

namespace emu::z80 {

    using emu::misc::NextByte;
    using emu::misc::NextWord;

    void adc_A_r(u8 &acc_reg, u8 value, Flags &flag_reg, unsigned long &cycles);
    void adc_A_n(u8 &acc_reg, NextByte args, Flags &flag_reg, unsigned long &cycles);
    void adc_A_MHL(u8 &acc_reg, u8 value, Flags &flag_reg, unsigned long &cycles);
    void adc_A_MixyPd(u8 &reg, u16 ixy_reg, const NextByte &args, const EmulatorMemory &memory, Flags &flag_reg, unsigned long &cycles);
    void adc_hl_ss(u8 &h_reg, u8 &l_reg, u16 value, Flags &flag_reg, unsigned long &cycles);
    void adc_A_ixy_h_or_l(u8 &acc_reg, u8 ixy_reg_h_or_l, Flags &flag_reg, unsigned long &cycles);
    void add_A_ixy_h_or_l(u8 &acc_reg, u8 ixy_reg, Flags &flag_reg, unsigned long &cycles);
    void add_A_MixyPd(u8 &reg, u16 ixy_reg, const NextByte &args, const EmulatorMemory &memory, Flags &flag_reg, unsigned long &cycles);
    void add_A_MHL(u8 &acc_reg, u8 value, Flags &flag_reg, unsigned long &cycles);
    void add_A_n(u8 &acc_reg, const NextByte &args, Flags &flag_reg, unsigned long &cycles);
    void add_A_r(u8 &acc_reg, u8 value, Flags &flag_reg, unsigned long &cycles);
    void add_HL_ss(u8 &h_reg, u8 &l_reg, u16 value, Flags &flag_reg, unsigned long &cycles);
    void add_ixy_pp(u16 &ix_reg, u16 value_to_add, Flags &flag_reg, unsigned long &cycles);
    void and_MixyPd(u8 &acc_reg, u16 ixy_reg, const NextByte &args, const EmulatorMemory &memory, Flags &flag_reg, unsigned long &cycles);
    void and_MHL(u8 &acc_reg, u8 value, Flags &flag_reg, unsigned long &cycles);
    void and_n(u8 &acc_reg, const NextByte &args, Flags &flag_reg, unsigned long &cycles);
    void and_r(u8 &acc_reg, u8 value, Flags &flag_reg, unsigned long &cycles);
    void and_ixy_h_or_l(u8 &acc_reg, u8 ixy_reg_h_or_l, Flags &flag_reg, unsigned long &cycles);
    void bit_r(unsigned int bit_number, u8 reg, Flags &flag_reg, unsigned long &cycles);
    void bit_MHL(unsigned int bit_number, u16 hl_reg, const EmulatorMemory &memory, Flags &flag_reg, unsigned long &cycles);
    void bit_MixyPd(unsigned int bit_number, u16 ixy_reg, u8 d, const EmulatorMemory &memory, Flags &flag_reg, unsigned long &cycles);
    void call(u16 &pc, u16 &sp, EmulatorMemory &memory, const NextWord &args, unsigned long &cycles);
    void call_nz(u16 &pc, u16 &sp, EmulatorMemory &memory, const NextWord &args, const Flags &flag_reg, unsigned long &cycles);
    void call_z(u16 &pc, u16 &sp, EmulatorMemory &memory, const NextWord &args, const Flags &flag_reg, unsigned long &cycles);
    void call_nc(u16 &pc, u16 &sp, EmulatorMemory &memory, const NextWord &args, const Flags &flag_reg, unsigned long &cycles);
    void call_c(u16 &pc, u16 &sp, EmulatorMemory &memory, const NextWord &args, const Flags &flag_reg, unsigned long &cycles);
    void call_po(u16 &pc, u16 &sp, EmulatorMemory &memory, const NextWord &args, const Flags &flag_reg, unsigned long &cycles);
    void call_pe(u16 &pc, u16 &sp, EmulatorMemory &memory, const NextWord &args, const Flags &flag_reg, unsigned long &cycles);
    void call_p(u16 &pc, u16 &sp, EmulatorMemory &memory, const NextWord &args, const Flags &flag_reg, unsigned long &cycles);
    void call_m(u16 &pc, u16 &sp, EmulatorMemory &memory, const NextWord &args, const Flags &flag_reg, unsigned long &cycles);
    void ccf(Flags &flag_reg, u8 acc_reg, unsigned long &cycles);
    void cpd(u8 &b_reg, u8 &c_reg, u8 &h_reg, u8 &l_reg, u8 acc_reg, const EmulatorMemory &memory, Flags &flag_reg, unsigned long &cycles);
    void cpdr(u16 &pc, u8 &b_reg, u8 &c_reg, u8 &h_reg, u8 &l_reg, u8 acc_reg, const EmulatorMemory &memory, Flags &flag_reg, unsigned long &cycles);
    void cpi(u8 &b_reg, u8 &c_reg, u8 &h_reg, u8 &l_reg, u8 acc_reg, const EmulatorMemory &memory, Flags &flag_reg, unsigned long &cycles);
    void cpir(u16 &pc, u8 &b_reg, u8 &c_reg, u8 &h_reg, u8 &l_reg, u8 acc_reg, const EmulatorMemory &memory, Flags &flag_reg, unsigned long &cycles);
    void cp_r(u8 &acc_reg, u8 value, Flags &flag_reg, unsigned long &cycles);
    void cp_n(u8 &acc_reg, const NextByte &args, Flags &flag_reg, unsigned long &cycles);
    void cp_MHL(u8 &acc_reg, u8 value, Flags &flag_reg, unsigned long &cycles);
    void cp_MixyPd(u8 &acc_reg, u16 ixy_reg, const NextByte &args, const EmulatorMemory &memory, Flags &flag_reg, unsigned long &cycles);
    void cp_ixy_h_or_l(u8 &acc_reg, u8 ixy_reg_h_or_l, Flags &flag_reg, unsigned long &cycles);
    void cpl(u8 &acc_reg, Flags &flag_reg, unsigned long &cycles);
    void daa(u8 &acc_reg, Flags &flag_reg, unsigned long &cycles);
    void dec_r(u8 &reg, Flags &flag_reg, unsigned long &cycles);
    void dec_r_undoc(u8 &reg, Flags &flag_reg, unsigned long &cycles);
    void dec_ss(u8 &reg1, u8 &reg2, unsigned long &cycles);
    void dec_sp(u16 &sp, unsigned long &cycles);
    void dec_MHL(u8 &value_in_hl, Flags &flag_reg, unsigned long &cycles);
    void dec_ixy(u16 &ix_or_iy, unsigned long &cycles);
    void dec_ixyh(u16 &ixy_reg, Flags &flag_reg, unsigned long &cycles);
    void dec_ixyl(u16 &ixy_reg, Flags &flag_reg, unsigned long &cycles);
    void dec_MixyPd(u16 ixy_reg, const NextByte &args, EmulatorMemory &memory, Flags &flag_reg, unsigned long &cycles);
    void di(bool &iff1, bool &iff2, unsigned long &cycles);
    void djnz(u8 &b_reg, u16 &pc, const NextByte &args, unsigned long &cycles);
    void ei(bool &iff1, bool &iff2, unsigned long &cycles);
    void ex(u8 &acc_reg, Flags &flag_reg, u8 &acc_p_reg, Flags &flag_p_reg, unsigned long &cycles);
    void ex_de_hl(u8 &h_reg, u8 &l_reg, u8 &d_reg, u8 &e_reg, unsigned long &cycles);
    void ex_msp_hl(u16 sp, EmulatorMemory &memory, u8 &h_reg, u8 &l_reg, unsigned long &cycles);
    void ex_msp_ixy(u16 sp, EmulatorMemory &memory, u16 &ixy_reg, unsigned long &cycles);
    void exx(u8 &b_reg, u8 &c_reg, u8 &b_p_reg, u8 &c_p_reg, u8 &d_reg, u8 &e_reg, u8 &d_p_reg, u8 &e_p_reg, u8 &h_reg, u8 &l_reg, u8 &h_p_reg, u8 &l_p_reg, unsigned long &cycles);
    void halt(bool &is_halted, unsigned long &cycles);
    void im(InterruptMode &interrupt_mode, InterruptMode value, unsigned long &cycles);
    void in_A_Mn(u8 &acc_reg, const NextByte &args, std::vector<u8> io, unsigned long &cycles);
    void inc_r(u8 &reg, Flags &flag_reg, unsigned long &cycles);
    void inc_r_undoc(u8 &reg, Flags &flag_reg, unsigned long &cycles);
    void inc_ss(u8 &reg1, u8 &reg2, unsigned long &cycles);
    void inc_MHL(u8 &value_in_hl, Flags &flag_reg, unsigned long &cycles);
    void inc_sp(u16 &sp, unsigned long &cycles);
    void inc_ixy(u16 &ixy_reg, unsigned long &cycles);
    void inc_ixyh(u16 &ixy_reg, Flags &flag_reg, unsigned long &cycles);
    void inc_ixyl(u16 &ixy_reg, Flags &flag_reg, unsigned long &cycles);
    void inc_MixyPd(u16 ixy_reg, const NextByte &args, EmulatorMemory &memory, Flags &flag_reg, unsigned long &cycles);
    void ind(u8 &b_reg, u8 c_reg, u8 &h_reg, u8 &l_reg, EmulatorMemory &memory, Flags &flag_reg, std::vector<u8> io, unsigned long &cycles);
    void indr(u16 &pc, u8 &b_reg, u8 c_reg, u8 &h_reg, u8 &l_reg, EmulatorMemory &memory, Flags &flag_reg, std::vector<u8> io, unsigned long &cycles);
    void ini(u8 &b_reg, u8 c_reg, u8 &h_reg, u8 &l_reg, EmulatorMemory &memory, Flags &flag_reg, std::vector<u8> io, unsigned long &cycles);
    void inir(u16 &pc, u8 &b_reg, u8 c_reg, u8 &h_reg, u8 &l_reg, EmulatorMemory &memory, Flags &flag_reg, std::vector<u8> io, unsigned long &cycles);
    void jp(u16 &pc, const NextWord &args, unsigned long &cycles);
    void jp_nz(u16 &pc, const NextWord &args, const Flags &flag_reg, unsigned long &cycles);
    void jp_z(u16 &pc, const NextWord &args, const Flags &flag_reg, unsigned long &cycles);
    void jp_nc(u16 &pc, const NextWord &args, const Flags &flag_reg, unsigned long &cycles);
    void jp_c(u16 &pc, const NextWord &args, const Flags &flag_reg, unsigned long &cycles);
    void jp_po(u16 &pc, const NextWord &args, const Flags &flag_reg, unsigned long &cycles);
    void jp_pe(u16 &pc, const NextWord &args, const Flags &flag_reg, unsigned long &cycles);
    void jp_p(u16 &pc, const NextWord &args, const Flags &flag_reg, unsigned long &cycles);
    void jp_m(u16 &pc, const NextWord &args, const Flags &flag_reg, unsigned long &cycles);
    void jp_hl(u16 &pc, u16 address, unsigned long &cycles);
    void jp_ixy(u16 &pc, u16 ixy_reg, unsigned long &cycles);
    void jr(u16 &pc, const NextByte &args, unsigned long &cycles);
    void jr_c(u16 &pc, const NextByte &args, const Flags &flag_reg, unsigned long &cycles);
    void jr_nc(u16 &pc, const NextByte &args, const Flags &flag_reg, unsigned long &cycles);
    void jr_nz(u16 &pc, const NextByte &args, const Flags &flag_reg, unsigned long &cycles);
    void jr_z(u16 &pc, const NextByte &args, const Flags &flag_reg, unsigned long &cycles);
    void ld_r_n(u8 &reg, const NextByte &args, unsigned long &cycles);
    void ld_r_n_undocumented(u8 &to, const NextByte &args, unsigned long &cycles);
    void ld_r_r(u8 &to, u8 value, unsigned long &cycles);
    void ld_r_r_undoc(u8 &to, u8 value, unsigned long &cycles);
    void ld_r_MHL(u8 &reg, u8 value, unsigned long &cycles);
    void ld_A_I(u8 &acc_reg, u8 i_reg, Flags &flag_reg, bool iff2, unsigned long &cycles);
    void ld_A_Mss(u8 &to, u8 value, unsigned long &cycles);
    void ld_A_Mnn(u8 &reg, const EmulatorMemory &memory, const NextWord &args, unsigned long &cycles);
    void ld_I_A(u8 &i_reg, u8 acc_reg, unsigned long &cycles);
    void ld_R_A(u8 &r_reg, u8 acc_reg, unsigned long &cycles);
    void ld_A_R(u8 &acc_reg, u8 r_reg, Flags &flag_reg, bool iff2, unsigned long &cycles);
    void ld_HL_Mnn(u8 &h_reg, u8 &l_reg, const EmulatorMemory &memory, const NextWord &args, unsigned long &cycles);
    void ld_dd_nn(u8 &reg1, u8 &reg2, const NextWord &args, unsigned long &cycles);
    void ld_ixy_nn(u16 &ixy_reg, const NextWord &args, unsigned long &cycles);
    void ld_dd_Mnn(u8 &reg1, u8 &reg2, const NextWord &args, const EmulatorMemory &memory, unsigned long &cycles);
    void ld_ixy_Mnn(u16 &ixy_reg, const NextWord &args, const EmulatorMemory &memory, unsigned long &cycles);
    void ld_ixyh_n(u16 &ixy_reg, const NextByte &args, unsigned long &cycles);
    void ld_ixyl_n(u16 &ixy_reg, const NextByte &args, unsigned long &cycles);
    void ld_ixyh_r_undoc(u16 &ixy_reg, u8 value, unsigned long &cycles);
    void ld_ixyl_r_undoc(u16 &ixy_reg, u8 value, unsigned long &cycles);
    void ld_r_MixyPd(u8 &reg, u16 ixy_reg, const NextByte &args, const EmulatorMemory &memory, unsigned long &cycles);
    void ld_MHL_n(u8 &reg, const NextByte &args, unsigned long &cycles);
    void ld_MHL_r(u8 &to, u8 value, unsigned long &cycles);
    void ld_MixyPd_n(u16 ixy_reg, const NextWord &args, EmulatorMemory &memory, unsigned long &cycles);
    void ld_MixyPd_r(u16 ixy_reg, const NextByte &args, EmulatorMemory &memory, u8 reg, unsigned long &cycles);
    void ld_Mnn_A(u8 &acc_reg, EmulatorMemory &memory, const NextWord &args, unsigned long &cycles);
    void ld_Mnn_HL(u8 h_reg, u8 l_reg, EmulatorMemory &memory, const NextWord &args, unsigned long &cycles);
    void ld_Mnn_dd(u8 hi_reg, u8 lo_reg, EmulatorMemory &memory, const NextWord &args, unsigned long &cycles);
    void ld_Mnn_sp(u16 sp, EmulatorMemory &memory, const NextWord &args, unsigned long &cycles);
    void ld_Mnn_ixy(u16 ixy_reg, const NextWord &args, EmulatorMemory &memory, unsigned long &cycles);
    void ld_Mss_A(u8 &to, u8 acc_reg, unsigned long &cycles);
    void ld_sp_Mnn(u16 &sp, EmulatorMemory memory, const NextWord &args, unsigned long &cycles);
    void ld_sp_nn(u16 &sp, const NextWord &args, unsigned long &cycles);
    void ld_sp_hl(u16 &sp, u16 address, unsigned long &cycles);
    void ld_sp_ixy(u16 &sp, u16 ixy, unsigned long &cycles);
    void ldd(u8 &b_reg, u8 &c_reg, u8 &d_reg, u8 &e_reg, u8 &h_reg, u8 &l_reg, u8 acc_reg, EmulatorMemory &memory, Flags &flag_reg, unsigned long &cycles);
    void lddr(u16 &pc, u8 &b_reg, u8 &c_reg, u8 &d_reg, u8 &e_reg, u8 &h_reg, u8 &l_reg, u8 acc_reg, EmulatorMemory &memory, Flags &flag_reg, unsigned long &cycles);
    void ldi(u8 &b_reg, u8 &c_reg, u8 &d_reg, u8 &e_reg, u8 &h_reg, u8 &l_reg, u8 acc_reg, EmulatorMemory &memory, Flags &flag_reg, unsigned long &cycles);
    void ldir(u16 &pc, u8 &b_reg, u8 &c_reg, u8 &d_reg, u8 &e_reg, u8 &h_reg, u8 &l_reg, u8 acc_reg, EmulatorMemory &memory, Flags &flag_reg, unsigned long &cycles);
    void neg(u8 &acc_reg, Flags &flag_reg, unsigned long &cycles);
    void nmi(u16 &pc, u16 &sp, EmulatorMemory &memory, unsigned long &cycles);
    void nop(unsigned long &cycles);
    void or_r(u8 &acc_reg, u8 value, Flags &flag_reg, unsigned long &cycles);
    void or_n(u8 &acc_reg, const NextByte &args, Flags &flag_reg, unsigned long &cycles);
    void or_MHL(u8 &acc_reg, u8 value, Flags &flag_reg, unsigned long &cycles);
    void or_MixyPd(u8 &acc_reg, u16 ixy_reg, const NextByte &args, const EmulatorMemory &memory, Flags &flag_reg, unsigned long &cycles);
    void or_ixy_h_or_l(u8 &acc_reg, u8 ixy_reg_h_or_l, Flags &flag_reg, unsigned long &cycles);
    void out_Mn_A(u8 acc_reg, const NextByte &args, std::vector<u8> &io, unsigned long &cycles);
    void outd(u8 &b_reg, u8 c_reg, u8 &h_reg, u8 &l_reg, EmulatorMemory &memory, Flags &flag_reg, std::vector<u8> io, unsigned long &cycles);
    void otdr(u16 &pc, u8 &b_reg, u8 c_reg, u8 &h_reg, u8 &l_reg, EmulatorMemory &memory, Flags &flag_reg, std::vector<u8> io, unsigned long &cycles);
    void otir(u16 &pc, u8 &b_reg, u8 c_reg, u8 &h_reg, u8 &l_reg, EmulatorMemory &memory, Flags &flag_reg, std::vector<u8> io, unsigned long &cycles);
    void outi(u8 &b_reg, u8 c_reg, u8 &h_reg, u8 &l_reg, EmulatorMemory &memory, Flags &flag_reg, std::vector<u8> io, unsigned long &cycles);
    void pop(u8 &reg1, u8 &reg2, u16 &sp, const EmulatorMemory &memory, unsigned long &cycles);
    void pop_af(Flags &flag_reg, u8 &acc_reg, u16 &sp, const EmulatorMemory &memory, unsigned long &cycles);
    void pop_ixy(u16 &ix_iy_reg, u16 &sp, const EmulatorMemory &memory, unsigned long &cycles);
    void push_qq(u8 reg1, u8 reg2, u16 &sp, EmulatorMemory &memory, unsigned long &cycles);
    void push_af(const Flags &flag_reg, u8 acc_reg, u16 &sp, EmulatorMemory &memory, unsigned long &cycles);
    void push_ixy(u16 ixy_reg, u16 &sp, EmulatorMemory &memory, unsigned long &cycles);
    void res_r(unsigned int bit_number, u8 &reg, unsigned long &cycles);
    void res_MHL(unsigned int bit_number, u16 hl_reg, EmulatorMemory &memory, unsigned long &cycles);
    void res_MixyPd(unsigned int bit_number, u16 ixy_reg, u8 d, EmulatorMemory &memory, unsigned long &cycles);
    void ret(u16 &pc, u16 &sp, const EmulatorMemory &memory, unsigned long &cycles);
    void ret_c(u16 &pc, u16 &sp, const EmulatorMemory &memory, const Flags &flag_reg, unsigned long &cycles);
    void ret_m(u16 &pc, u16 &sp, EmulatorMemory &memory, const Flags &flag_reg, unsigned long &cycles);
    void ret_nc(u16 &pc, u16 &sp, const EmulatorMemory &memory, const Flags &flag_reg, unsigned long &cycles);
    void ret_nz(u16 &pc, u16 &sp, const EmulatorMemory &memory, const Flags &flag_reg, unsigned long &cycles);
    void ret_p(u16 &pc, u16 &sp, const EmulatorMemory &memory, const Flags &flag_reg, unsigned long &cycles);
    void ret_pe(u16 &pc, u16 &sp, const EmulatorMemory &memory, const Flags &flag_reg, unsigned long &cycles);
    void ret_po(u16 &pc, u16 &sp, const EmulatorMemory &memory, const Flags &flag_reg, unsigned long &cycles);
    void ret_z(u16 &pc, u16 &sp, const EmulatorMemory &memory, const Flags &flag_reg, unsigned long &cycles);
    void reti(u16 &pc, u16 &sp, const EmulatorMemory &memory, unsigned long &cycles);
    void retn(u16 &pc, u16 &sp, const EmulatorMemory &memory, bool &iff1, bool iff2, unsigned long &cycles);
    void rla(u8 &acc_reg, Flags &flag_reg, unsigned long &cycles);
    void rl_r(u8 &reg, Flags &flag_reg, unsigned long &cycles);
    void rl_MHL(u8 &value_in_hl, Flags &flag_reg, unsigned long &cycles);
    void rl_MixyPd(u16 ixy_reg, u8 d, EmulatorMemory &memory, Flags &flag_reg, unsigned long &cycles);
    void rlca(u8 &acc_reg, Flags &flag_reg, unsigned long &cycles);
    void rlc_r(u8 &reg, Flags &flag_reg, unsigned long &cycles);
    void rlc_MHL(u8 &value_in_hl, Flags &flag_reg, unsigned long &cycles);
    void rlc_MixyPd(u16 ixy_reg, u8 d, EmulatorMemory &memory, Flags &flag_reg, unsigned long &cycles);
    void rlc_MixyPd_r(u8 &reg, u16 ixy_reg, u8 d, EmulatorMemory &memory, Flags &flag_reg, unsigned long &cycles);
    void rld(u8 &acc_reg, u8 &value, Flags &flag_reg, unsigned long &cycles);
    void rra(u8 &acc_reg, Flags &flag_reg, unsigned long &cycles);
    void rr_r(u8 &reg, Flags &flag_reg, unsigned long &cycles);
    void rr_MHL(u8 &value_in_hl, Flags &flag_reg, unsigned long &cycles);
    void rr_MixyPd(u16 ixy_reg, u8 d, EmulatorMemory &memory, Flags &flag_reg, unsigned long &cycles);
    void rrca(u8 &acc_reg, Flags &flag_reg, unsigned long &cycles);
    void rrc_r(u8 &reg, Flags &flag_reg, unsigned long &cycles);
    void rrc_MHL(u8 &value_in_hl, Flags &flag_reg, unsigned long &cycles);
    void rrc_MixyPd(u16 ixy_reg, u8 d, EmulatorMemory &memory, Flags &flag_reg, unsigned long &cycles);
    void rrc_MixyPd_r(u8 &reg, u16 ixy_reg, u8 d, EmulatorMemory &memory, Flags &flag_reg, unsigned long &cycles);
    void rrd(u8 &acc_reg, u8 &value, Flags &flag_reg, unsigned long &cycles);
    void rst_0(u16 &pc, u16 &sp, EmulatorMemory &memory, unsigned long &cycles);
    void rst_1(u16 &pc, u16 &sp, EmulatorMemory &memory, unsigned long &cycles);
    void rst_2(u16 &pc, u16 &sp, EmulatorMemory &memory, unsigned long &cycles);
    void rst_3(u16 &pc, u16 &sp, EmulatorMemory &memory, unsigned long &cycles);
    void rst_4(u16 &pc, u16 &sp, EmulatorMemory &memory, unsigned long &cycles);
    void rst_5(u16 &pc, u16 &sp, EmulatorMemory &memory, unsigned long &cycles);
    void rst_6(u16 &pc, u16 &sp, EmulatorMemory &memory, unsigned long &cycles);
    void rst_7(u16 &pc, u16 &sp, EmulatorMemory &memory, unsigned long &cycles);
    void sbc_A_r(u8 &acc_reg, u8 value, Flags &flag_reg, unsigned long &cycles);
    void sbc_A_n(u8 &acc_reg, const NextByte &args, Flags &flag_reg, unsigned long &cycles);
    void sbc_A_MHL(u8 &acc_reg, u8 value, Flags &flag_reg, unsigned long &cycles);
    void sbc_A_MixyPd(u8 &acc_reg, u16 ixy_reg, const NextByte &args, const EmulatorMemory &memory, Flags &flag_reg, unsigned long &cycles);
    void sbc_HL_ss(u8 &h_reg, u8 &l_reg, u16 value, Flags &flag_reg, unsigned long &cycles);
    void sbc_A_ixy_h_or_l(u8 &acc_reg, u8 ixy_reg_h_or_l, Flags &flag_reg, unsigned long &cycles);
    void scf(Flags &flag_reg, u8 acc_reg, unsigned long &cycles);
    void set_r(unsigned int bit_number, u8 &reg, unsigned long &cycles);
    void set_MHL(unsigned int bit_number, u16 hl_reg, EmulatorMemory &memory, unsigned long &cycles);
    void set_MixyPd(unsigned int bit_number, u16 ixy_reg, u8 d, EmulatorMemory &memory, unsigned long &cycles);
    void sla_r(u8 &reg, Flags &flag_reg, unsigned long &cycles);
    void sla_MHL(u8 &value_in_hl, Flags &flag_reg, unsigned long &cycles);
    void sla_MixyPd(u16 ixy_reg, u8 d, EmulatorMemory &memory, Flags &flag_reg, unsigned long &cycles);
    void sla_MixyPd_r(u8 &reg, u16 ixy_reg, const NextByte &args, EmulatorMemory &memory, Flags &flag_reg, unsigned long &cycles);
    void sll_r(u8 &reg, Flags &flag_reg, unsigned long &cycles);
    void sll_MHL(u8 &value_in_hl, Flags &flag_reg, unsigned long &cycles);
    void sll_MixyPd(u16 ixy_reg, u8 d, EmulatorMemory &memory, Flags &flag_reg, unsigned long &cycles);
    void sll_MixyPd_r(u8 &reg, u16 ixy_reg, u8 d, EmulatorMemory &memory, Flags &flag_reg, unsigned long &cycles);
    void sra_r(u8 &reg, Flags &flag_reg, unsigned long &cycles);
    void sra_MHL(u8 &value_in_hl, Flags &flag_reg, unsigned long &cycles);
    void sra_MixyPd(u16 ixy_reg, u8 d, EmulatorMemory &memory, Flags &flag_reg, unsigned long &cycles);
    void sra_MixyPd_r(u8 &reg, u16 ixy_reg, u8 d, EmulatorMemory &memory, Flags &flag_reg, unsigned long &cycles);
    void srl_r(u8 &reg, Flags &flag_reg, unsigned long &cycles);
    void srl_MHL(u8 &value_in_hl, Flags &flag_reg, unsigned long &cycles);
    void srl_MixyPd(u16 ixy_reg, u8 d, EmulatorMemory &memory, Flags &flag_reg, unsigned long &cycles);
    void srl_MixyPd_r(u8 &reg, u16 ixy_reg, u8 d, EmulatorMemory &memory, Flags &flag_reg, unsigned long &cycles);
    void sub_MixyPd(u8 &acc_reg, u16 ixy_reg, const NextByte &args, const EmulatorMemory &memory, Flags &flag_reg, unsigned long &cycles);
    void sub_ixy_h_or_l(u8 &acc_reg, u8 ixy_reg_h_or_l, Flags &flag_reg, unsigned long &cycles);
    void sub_n(u8 &acc_reg, const NextByte &args, Flags &flag_reg, unsigned long &cycles);
    void sub_r(u8 &acc_reg, u8 value, Flags &flag_reg, unsigned long &cycles);
    void sub_MHL(u8 &acc_reg, u8 value, Flags &flag_reg, unsigned long &cycles);
    void xor_n(u8 &acc_reg, const NextByte &args, Flags &flag_reg, unsigned long &cycles);
    void xor_r(u8 &acc_reg, u8 value, Flags &flag_reg, unsigned long &cycles);
    void xor_MHL(u8 &acc_reg, u8 value, Flags &flag_reg, unsigned long &cycles);
    void xor_MixyPd(u8 &acc_reg, u16 ixy_reg, const NextByte &args, const EmulatorMemory &memory, Flags &flag_reg, unsigned long &cycles);
    void xor_ixy_h_or_l(u8 &acc_reg, u8 ixy_reg_h_or_l, Flags &flag_reg, unsigned long &cycles);

    void print_adc_r_s(std::ostream &ostream, const std::string &dest, const std::string &src);
    void print_adc_r_s_undocumented(std::ostream &ostream, const std::string &dest, const std::string &src);
    void print_adc_r_n(std::ostream &ostream, const std::string &reg, const NextByte &args);
    void print_adc_MixyPn(std::ostream &ostream, const std::string &reg, const std::string &ixy_reg, const NextByte &args);
    void print_add(std::ostream &ostream, const std::string &dest, const std::string &src);
    void print_add_undocumented(std::ostream &ostream, const std::string &dest, const std::string &src);
    void print_add_r_n(std::ostream &ostream, const std::string &reg, const NextByte &args);
    void print_and_r(std::ostream &ostream, const std::string &reg);
    void print_and_r_undocumented(std::ostream &ostream, const std::string &reg);
    void print_and_MixyPn(std::ostream &ostream, const std::string &ixy_reg, const NextByte &args);
    void print_and_n(std::ostream &ostream, const NextByte &args);
    void print_add_MixyPn(std::ostream &ostream, const std::string &reg, const std::string &ixy_reg, const NextByte &args);
    void print_bit(std::ostream &ostream, unsigned int bit_number, const std::string &src);
    void print_bit_MixyPn(std::ostream &ostream, unsigned int bit_number, const std::string &ixy_reg, u8 d);
    void print_call_nn(std::ostream &ostream, const NextWord &args);
    void print_call_cc_nn(std::ostream &ostream, const NextWord &args, const std::string &condition);
    void print_ccf(std::ostream &ostream);
    void print_cp(std::ostream &ostream, const std::string &reg);
    void print_cp_undocumented(std::ostream &ostream, const std::string &reg);
    void print_cp(std::ostream &ostream, const NextByte &args);
    void print_cp_MixyPn(std::ostream &ostream, const std::string &ixy_reg, const NextByte &args);
    void print_cpd(std::ostream &ostream);
    void print_cpdr(std::ostream &ostream);
    void print_cpi(std::ostream &ostream);
    void print_cpir(std::ostream &ostream);
    void print_cpl(std::ostream &ostream);
    void print_daa(std::ostream &ostream);
    void print_di(std::ostream &ostream);
    void print_djnz(std::ostream &ostream, const NextByte &args);
    void print_dec(std::ostream &ostream, const std::string &reg);
    void print_dec_undocumented(std::ostream &ostream, const std::string &reg);
    void print_dec_MixyPn(std::ostream &ostream, const std::string &ixy_reg, const NextByte &args);
    void print_ei(std::ostream &ostream);
    void print_ex(std::ostream &ostream, const std::string& reg, const std::string& comp_reg);
    void print_exx(std::ostream &ostream);
    void print_halt(std::ostream &ostream);
    void print_im(std::ostream &ostream, unsigned int interrupt_mode);
    void print_in(std::ostream &ostream, const NextByte &args);
    void print_in_undocumented(std::ostream &ostream, const std::string& dest);
    void print_in_r_Mr(std::ostream &ostream, const std::string& dest, const std::string& src);
    void print_inc(std::ostream &ostream, const std::string &reg);
    void print_inc_MixyPn(std::ostream &ostream, const std::string &ixy_reg, const NextByte &args);
    void print_inc_undocumented(std::ostream &ostream, const std::string &reg);
    void print_ind(std::ostream &ostream);
    void print_indr(std::ostream &ostream);
    void print_ini(std::ostream &ostream);
    void print_inir(std::ostream &ostream);
    void print_jp_nn(std::ostream &ostream, const NextWord &args);
    void print_jp_cc_nn(std::ostream &ostream, const NextWord &args, const std::string &condition);
    void print_jp_Mss(std::ostream &ostream, const std::string& reg);
    void print_jr(std::ostream &ostream, const NextByte &args);
    void print_jr(std::ostream &ostream, const std::string &condition, const NextByte &args);
    void print_ld(std::ostream &ostream, const std::string &dest, const std::string &src);
    void print_ld_undocumented(std::ostream &ostream, const std::string &dest, const std::string &src);
    void print_ld(std::ostream &ostream, const std::string &dest, const NextByte &args);
    void print_ld_undocumented(std::ostream &ostream, const std::string &dest, const NextByte &args);
    void print_ld(std::ostream &ostream, const std::string &dest, const NextWord &args);
    void print_ld_dd_nn(std::ostream &ostream, const std::string &reg, const NextWord &args);
    void print_ld_Mnn_dd(std::ostream &ostream, const NextWord &args, const std::string &src);
    void print_ld_Mnn_dd_undocumented(std::ostream &ostream, const NextWord &args, const std::string &src);
    void print_ld_dd_Mnn(std::ostream &ostream, const std::string &dest, const NextWord &args);
    void print_ld_dd_Mnn_undocumented(std::ostream &ostream, const std::string &dest, const NextWord &args);
    void print_ld_MixyPd_n(std::ostream &ostream, const std::string &ixy_reg, const NextWord &args);
    void print_ld_MixyPd_r(std::ostream &ostream, const std::string &ixy_reg, const NextByte &args, const std::string &reg);
    void print_ld_r_MixyPn(std::ostream &ostream, const std::string &dest, const std::string &ixy_reg, const NextByte &args);
    void print_ldd(std::ostream &ostream);
    void print_lddr(std::ostream &ostream);
    void print_ldi(std::ostream &ostream);
    void print_ldir(std::ostream &ostream);
    void print_neg(std::ostream &ostream);
    void print_nop(std::ostream &ostream);
    void print_or_r(std::ostream &ostream, const std::string &reg);
    void print_or_r_undocumented(std::ostream &ostream, const std::string &reg);
    void print_or_MixyPn(std::ostream &ostream, const std::string &ixy_reg, const NextByte &args);
    void print_or_n(std::ostream &ostream, const NextByte &args);
    void print_pop(std::ostream &ostream, const std::string &reg);
    void print_push(std::ostream &ostream, const std::string &reg);
    void print_out(std::ostream &ostream, const NextByte &args);
    void print_out_Mr_r(std::ostream &ostream, const std::string& dest, const std::string& src);
    void print_out_Mr_r_undocumented(std::ostream &ostream, const std::string& dest, const std::string& src);
    void print_outd(std::ostream &ostream);
    void print_outi(std::ostream &ostream);
    void print_otdr(std::ostream &ostream);
    void print_otir(std::ostream &ostream);
    void print_res(std::ostream &ostream, unsigned int bit_number, const std::string &src);
    void print_res_MixyPn(std::ostream &ostream, unsigned int bit_number, const std::string &ixy_reg, u8 d);
    void print_ret(std::ostream &ostream);
    void print_ret(std::ostream &ostream, const std::string& condition);
    void print_reti(std::ostream &ostream);
    void print_retn(std::ostream &ostream);
    void print_rla(std::ostream &ostream);
    void print_rl(std::ostream &ostream, const std::string &reg);
    void print_rl_MixyPn(std::ostream &ostream, const std::string &ixy_reg, u8 d);
    void print_rl_MixyPn_r(std::ostream &ostream, const std::string &ixy_reg, u8 d, const std::string &reg);
    void print_rlc(std::ostream &ostream, const std::string &reg);
    void print_rlc_MixyPn(std::ostream &ostream, const std::string &ixy_reg, u8 d);
    void print_rlc_MixyPn_r(std::ostream &ostream, const std::string &ixy_reg, u8 d, const std::string &reg);
    void print_rlca(std::ostream &ostream);
    void print_rld(std::ostream &ostream);
    void print_rst(std::ostream &ostream, int number);
    void print_rr(std::ostream &ostream, const std::string &reg);
    void print_rr_MixyPn(std::ostream &ostream, const std::string &ixy_reg, u8 d);
    void print_rra(std::ostream &ostream);
    void print_rrc(std::ostream &ostream, const std::string &reg);
    void print_rrc_MixyPn(std::ostream &ostream, const std::string &ixy_reg, u8 d);
    void print_rrca(std::ostream &ostream);
    void print_rrd(std::ostream &ostream);
    void print_sbc_r_s(std::ostream &ostream, const std::string &dest, const std::string &src);
    void print_sbc_r_s_undocumented(std::ostream &ostream, const std::string &dest, const std::string &src);
    void print_sbc_r_n(std::ostream &ostream, const std::string &reg, const NextByte &args);
    void print_sbc_MixyPn(std::ostream &ostream, const std::string &reg, const std::string &ixy_reg, const NextByte &args);
    void print_scf(std::ostream &ostream);
    void print_set(std::ostream &ostream, unsigned int bit_number, const std::string &src);
    void print_set_MixyPn(std::ostream &ostream, unsigned int bit_number, const std::string &ixy_reg, u8 d);
    void print_sla(std::ostream &ostream, const std::string &reg);
    void print_sla_MixyPn(std::ostream &ostream, unsigned int bit_number, const std::string &ixy_reg, u8 d);
    void print_sra(std::ostream &ostream, const std::string &reg);
    void print_sra_MixyPn(std::ostream &ostream, unsigned int bit_number, const std::string &ixy_reg, u8 d);
    void print_sll(std::ostream &ostream, const std::string &reg);
    void print_sll_MixyPn(std::ostream &ostream, unsigned int bit_number, const std::string &ixy_reg, u8 d);
    void print_srl(std::ostream &ostream, const std::string &reg);
    void print_srl_MixyPn(std::ostream &ostream, unsigned int bit_number, const std::string &ixy_reg, u8 d);
    void print_sub(std::ostream &ostream, const std::string &reg);
    void print_sub_undocumented(std::ostream &ostream, const std::string &reg);
    void print_sub(std::ostream &ostream, const NextByte &args);
    void print_sub_MixyPn(std::ostream &ostream, const std::string &ixy_reg, const NextByte &args);
    void print_xor_r(std::ostream &ostream, const std::string &reg);
    void print_xor_r_undocumented(std::ostream &ostream, const std::string &reg);
    void print_xor_n(std::ostream &ostream, const NextByte &args);
    void print_xor_MixyPn(std::ostream &ostream, const std::string &ixy_reg, const NextByte &args);
}
// @formatter:on

#endif //MIKA_EMULATORS_Z80_INSTRUCTIONS_INSTRUCTIONS_H
