#ifndef MIKA_EMULATORS_CROSSCUTTING_GUI_GUI_TYPE_H
#define MIKA_EMULATORS_CROSSCUTTING_GUI_GUI_TYPE_H

namespace emu::gui {

    enum GuiType {
        ORDINARY,
        DEBUGGING
    };
}

#endif //MIKA_EMULATORS_CROSSCUTTING_GUI_GUI_TYPE_H
