set(SOURCES_8080_CPP
        src/chips/8080/cpu.cpp
        src/chips/8080/disassembler8080.cpp
        src/chips/8080/emulator_memory.cpp
        src/chips/8080/flags.cpp
        src/chips/8080/shift_register.cpp
        src/chips/8080/instructions/aci.cpp
        src/chips/8080/instructions/adc.cpp
        src/chips/8080/instructions/add.cpp
        src/chips/8080/instructions/adi.cpp
        src/chips/8080/instructions/ana.cpp
        src/chips/8080/instructions/ani.cpp
        src/chips/8080/instructions/call.cpp
        src/chips/8080/instructions/cc.cpp
        src/chips/8080/instructions/cm.cpp
        src/chips/8080/instructions/cma.cpp
        src/chips/8080/instructions/cmc.cpp
        src/chips/8080/instructions/cmp.cpp
        src/chips/8080/instructions/cnc.cpp
        src/chips/8080/instructions/cnz.cpp
        src/chips/8080/instructions/cp.cpp
        src/chips/8080/instructions/cpe.cpp
        src/chips/8080/instructions/cpi.cpp
        src/chips/8080/instructions/cpo.cpp
        src/chips/8080/instructions/cz.cpp
        src/chips/8080/instructions/daa.cpp
        src/chips/8080/instructions/dad.cpp
        src/chips/8080/instructions/dcr.cpp
        src/chips/8080/instructions/dcx.cpp
        src/chips/8080/instructions/di.cpp
        src/chips/8080/instructions/ei.cpp
        src/chips/8080/instructions/hlt.cpp
        src/chips/8080/instructions/in.cpp
        src/chips/8080/instructions/inr.cpp
        src/chips/8080/instructions/instruction_util.cpp
        src/chips/8080/instructions/inx.cpp
        src/chips/8080/instructions/jc.cpp
        src/chips/8080/instructions/jm.cpp
        src/chips/8080/instructions/jmp.cpp
        src/chips/8080/instructions/jnc.cpp
        src/chips/8080/instructions/jnz.cpp
        src/chips/8080/instructions/jp.cpp
        src/chips/8080/instructions/jpe.cpp
        src/chips/8080/instructions/jpo.cpp
        src/chips/8080/instructions/jz.cpp
        src/chips/8080/instructions/lda.cpp
        src/chips/8080/instructions/ldax.cpp
        src/chips/8080/instructions/lhld.cpp
        src/chips/8080/instructions/lxi.cpp
        src/chips/8080/instructions/mov.cpp
        src/chips/8080/instructions/mvi.cpp
        src/chips/8080/instructions/nop.cpp
        src/chips/8080/instructions/ora.cpp
        src/chips/8080/instructions/ori.cpp
        src/chips/8080/instructions/out.cpp
        src/chips/8080/instructions/pchl.cpp
        src/chips/8080/instructions/pop.cpp
        src/chips/8080/instructions/push.cpp
        src/chips/8080/instructions/ral.cpp
        src/chips/8080/instructions/rar.cpp
        src/chips/8080/instructions/rc.cpp
        src/chips/8080/instructions/ret.cpp
        src/chips/8080/instructions/rlc.cpp
        src/chips/8080/instructions/rm.cpp
        src/chips/8080/instructions/rnc.cpp
        src/chips/8080/instructions/rnz.cpp
        src/chips/8080/instructions/rp.cpp
        src/chips/8080/instructions/rpe.cpp
        src/chips/8080/instructions/rpo.cpp
        src/chips/8080/instructions/rrc.cpp
        src/chips/8080/instructions/rst.cpp
        src/chips/8080/instructions/rz.cpp
        src/chips/8080/instructions/sbb.cpp
        src/chips/8080/instructions/sbi.cpp
        src/chips/8080/instructions/shld.cpp
        src/chips/8080/instructions/sphl.cpp
        src/chips/8080/instructions/sta.cpp
        src/chips/8080/instructions/stax.cpp
        src/chips/8080/instructions/stc.cpp
        src/chips/8080/instructions/sub.cpp
        src/chips/8080/instructions/sui.cpp
        src/chips/8080/instructions/unused.cpp
        src/chips/8080/instructions/xchg.cpp
        src/chips/8080/instructions/xra.cpp
        src/chips/8080/instructions/xri.cpp
        src/chips/8080/instructions/xthl.cpp
        )

set(SOURCES_8080_H
        src/chips/8080/cpu.h
        src/chips/8080/disassembler8080.h
        src/chips/8080/emulator_memory.h
        src/chips/8080/flags.h
        src/chips/8080/shift_register.h
        src/chips/8080/instructions/instruction_util.h
        src/chips/8080/instructions/instructions.h
        src/chips/8080/interfaces/gui_observer.h
        src/chips/8080/interfaces/in_observer.h
        src/chips/8080/interfaces/out_observer.h
        )
