set(SOURCES_IMGUI
        libs/imgui/imconfig.h
        libs/imgui/imgui.cpp
        libs/imgui/imgui.h
        libs/imgui/imgui_demo.cpp
        libs/imgui/imgui_draw.cpp
        libs/imgui/imgui_impl_opengl3.cpp
        libs/imgui/imgui_impl_opengl3.h
        libs/imgui/imgui_impl_opengl3_loader.h
        libs/imgui/imgui_impl_sdl.cpp
        libs/imgui/imgui_impl_sdl.h
        libs/imgui/imgui_internal.h
        libs/imgui/imgui_memory_editor.h
        libs/imgui/imgui_tables.cpp
        libs/imgui/imgui_widgets.cpp
        libs/imgui/imstb_rectpack.h
        libs/imgui/imstb_textedit.h
        libs/imgui/imstb_truetype.h
        )
