set(SOURCES_CROSSCUTTING_CPP
        src/main.cpp
        src/crosscutting/debugging/breakpoint.cpp
        src/crosscutting/debugging/debugger.cpp
        src/crosscutting/debugging/debug_container.cpp
        src/crosscutting/debugging/disassembled_line.cpp
        src/crosscutting/exceptions/invalid_program_arguments_exception.cpp
        src/crosscutting/exceptions/unrecognized_opcode_exception.cpp
        src/crosscutting/gui/debugging_panes/cpu_info_pane.cpp
        src/crosscutting/gui/debugging_panes/debug_log_pane.cpp
        src/crosscutting/gui/debugging_panes/disassembly_pane.cpp
        src/crosscutting/gui/debugging_panes/io_info_pane.cpp
        src/crosscutting/gui/debugging_panes/memory_editor_pane.cpp
        src/crosscutting/gui/debugging_panes/spritemap_pane.cpp
        src/crosscutting/gui/debugging_panes/tilemap_pane.cpp
        src/crosscutting/gui/debugging_panes/waveform_pane.cpp
        src/crosscutting/gui/graphics/color.cpp
        src/crosscutting/gui/graphics/framebuffer.cpp
        src/crosscutting/gui/graphics/palette.cpp
        src/crosscutting/gui/graphics/sprite.cpp
        src/crosscutting/gui/graphics/tile.cpp
        src/crosscutting/logging/logger.cpp
        src/crosscutting/misc/governor.cpp
        src/crosscutting/misc/sdl_counter.cpp
        src/crosscutting/util/byte_util.cpp
        src/crosscutting/util/file_util.cpp
        src/crosscutting/util/gui_util.cpp
        src/crosscutting/util/string_util.cpp
        )

set(SOURCES_CROSSCUTTING_H
        src/crosscutting/typedefs.h
        src/crosscutting/debugging/breakpoint.h
        src/crosscutting/debugging/debugger.h
        src/crosscutting/debugging/debug_container.h
        src/crosscutting/debugging/disassembled_line.h
        src/crosscutting/exceptions/invalid_program_arguments_exception.h
        src/crosscutting/exceptions/unrecognized_opcode_exception.h
        src/crosscutting/gui/gui_type.h
        src/crosscutting/gui/debugging_panes/disassembly_pane.h
        src/crosscutting/gui/debugging_panes/cpu_info_pane.h
        src/crosscutting/gui/debugging_panes/debug_log_pane.h
        src/crosscutting/gui/debugging_panes/io_info_pane.h
        src/crosscutting/gui/debugging_panes/memory_editor_pane.h
        src/crosscutting/gui/debugging_panes/spritemap_pane.h
        src/crosscutting/gui/debugging_panes/tilemap_pane.h
        src/crosscutting/gui/debugging_panes/waveform_pane.h
        src/crosscutting/gui/graphics/color.h
        src/crosscutting/gui/graphics/framebuffer.h
        src/crosscutting/gui/graphics/palette.h
        src/crosscutting/gui/graphics/sprite.h
        src/crosscutting/gui/graphics/tile.h
        src/crosscutting/logging/log_observer.h
        src/crosscutting/logging/logger.h
        src/crosscutting/misc/emulator.h
        src/crosscutting/misc/governor.h
        src/crosscutting/misc/run_status.h
        src/crosscutting/misc/sdl_counter.h
        src/crosscutting/misc/session.h
        src/crosscutting/misc/next_byte.h
        src/crosscutting/misc/next_word.h
        src/crosscutting/util/byte_util.h
        src/crosscutting/util/file_util.h
        src/crosscutting/util/gui_util.h
        src/crosscutting/util/string_util.h
        )
