set(TEST_SOURCES_8080_CPP
        src/8080/cpu.cpp
        src/8080/emulator_memory.cpp
        src/8080/flags.cpp
        src/8080/instructions/aci.cpp
        src/8080/instructions/adc.cpp
        src/8080/instructions/add.cpp
        src/8080/instructions/adi.cpp
        src/8080/instructions/ana.cpp
        src/8080/instructions/ani.cpp
        src/8080/instructions/call.cpp
        src/8080/instructions/cc.cpp
        src/8080/instructions/cm.cpp
        src/8080/instructions/cma.cpp
        src/8080/instructions/cmc.cpp
        src/8080/instructions/cmp.cpp
        src/8080/instructions/cnc.cpp
        src/8080/instructions/cnz.cpp
        src/8080/instructions/cp.cpp
        src/8080/instructions/cpe.cpp
        src/8080/instructions/cpi.cpp
        src/8080/instructions/cpo.cpp
        src/8080/instructions/cz.cpp
        src/8080/instructions/daa.cpp
        src/8080/instructions/dad.cpp
        src/8080/instructions/dcr.cpp
        src/8080/instructions/dcx.cpp
        src/8080/instructions/di.cpp
        src/8080/instructions/ei.cpp
        src/8080/instructions/hlt.cpp
        src/8080/instructions/in.cpp
        src/8080/instructions/inr.cpp
        src/8080/instructions/instruction_util.cpp
        src/8080/instructions/inx.cpp
        src/8080/instructions/jc.cpp
        src/8080/instructions/jm.cpp
        src/8080/instructions/jmp.cpp
        src/8080/instructions/jnc.cpp
        src/8080/instructions/jnz.cpp
        src/8080/instructions/jp.cpp
        src/8080/instructions/jpe.cpp
        src/8080/instructions/jpo.cpp
        src/8080/instructions/jz.cpp
        src/8080/instructions/lda.cpp
        src/8080/instructions/ldax.cpp
        src/8080/instructions/lhld.cpp
        src/8080/instructions/lxi.cpp
        src/8080/instructions/mov.cpp
        src/8080/instructions/mvi.cpp
        src/8080/instructions/nop.cpp
        src/8080/instructions/ora.cpp
        src/8080/instructions/ori.cpp
        src/8080/instructions/out.cpp
        src/8080/instructions/pchl.cpp
        src/8080/instructions/pop.cpp
        src/8080/instructions/push.cpp
        src/8080/instructions/ral.cpp
        src/8080/instructions/rar.cpp
        src/8080/instructions/rc.cpp
        src/8080/instructions/ret.cpp
        src/8080/instructions/rlc.cpp
        src/8080/instructions/rm.cpp
        src/8080/instructions/rnc.cpp
        src/8080/instructions/rnz.cpp
        src/8080/instructions/rp.cpp
        src/8080/instructions/rpe.cpp
        src/8080/instructions/rpo.cpp
        src/8080/instructions/rrc.cpp
        src/8080/instructions/rst.cpp
        src/8080/instructions/rz.cpp
        src/8080/instructions/sbb.cpp
        src/8080/instructions/sbi.cpp
        src/8080/instructions/shld.cpp
        src/8080/instructions/sphl.cpp
        src/8080/instructions/sta.cpp
        src/8080/instructions/stax.cpp
        src/8080/instructions/stc.cpp
        src/8080/instructions/sub.cpp
        src/8080/instructions/sui.cpp
        src/8080/instructions/unused.cpp
        src/8080/instructions/xchg.cpp
        src/8080/instructions/xra.cpp
        src/8080/instructions/xri.cpp
        src/8080/instructions/xthl.cpp
        src/8080/instructions/tests/aci.cpp
        src/8080/instructions/tests/adc.cpp
        src/8080/instructions/tests/add.cpp
        src/8080/instructions/tests/adi.cpp
        src/8080/instructions/tests/ana.cpp
        src/8080/instructions/tests/ani.cpp
        src/8080/instructions/tests/call.cpp
        src/8080/instructions/tests/cc.cpp
        src/8080/instructions/tests/cm.cpp
        src/8080/instructions/tests/cma.cpp
        src/8080/instructions/tests/cmc.cpp
        src/8080/instructions/tests/cmp.cpp
        src/8080/instructions/tests/cnc.cpp
        src/8080/instructions/tests/cnz.cpp
        src/8080/instructions/tests/cp.cpp
        src/8080/instructions/tests/cpe.cpp
        src/8080/instructions/tests/cpi.cpp
        src/8080/instructions/tests/cpo.cpp
        src/8080/instructions/tests/cz.cpp
        src/8080/instructions/tests/daa.cpp
        src/8080/instructions/tests/dad.cpp
        src/8080/instructions/tests/dcr.cpp
        src/8080/instructions/tests/dcx.cpp
        src/8080/instructions/tests/di.cpp
        src/8080/instructions/tests/ei.cpp
        src/8080/instructions/tests/hlt.cpp
        src/8080/instructions/tests/in.cpp
        src/8080/instructions/tests/inr.cpp
        src/8080/instructions/tests/inx.cpp
        src/8080/instructions/tests/jc.cpp
        src/8080/instructions/tests/jm.cpp
        src/8080/instructions/tests/jmp.cpp
        src/8080/instructions/tests/jnc.cpp
        src/8080/instructions/tests/jnz.cpp
        src/8080/instructions/tests/jp.cpp
        src/8080/instructions/tests/jpe.cpp
        src/8080/instructions/tests/jpo.cpp
        src/8080/instructions/tests/jz.cpp
        src/8080/instructions/tests/lda.cpp
        src/8080/instructions/tests/ldax.cpp
        src/8080/instructions/tests/lhld.cpp
        src/8080/instructions/tests/lxi.cpp
        src/8080/instructions/tests/mov.cpp
        src/8080/instructions/tests/mvi.cpp
        src/8080/instructions/tests/nop.cpp
        src/8080/instructions/tests/ora.cpp
        src/8080/instructions/tests/ori.cpp
        src/8080/instructions/tests/out.cpp
        src/8080/instructions/tests/pchl.cpp
        src/8080/instructions/tests/pop.cpp
        src/8080/instructions/tests/push.cpp
        src/8080/instructions/tests/ral.cpp
        src/8080/instructions/tests/rar.cpp
        src/8080/instructions/tests/rc.cpp
        src/8080/instructions/tests/ret.cpp
        src/8080/instructions/tests/rlc.cpp
        src/8080/instructions/tests/rm.cpp
        src/8080/instructions/tests/rnc.cpp
        src/8080/instructions/tests/rnz.cpp
        src/8080/instructions/tests/rp.cpp
        src/8080/instructions/tests/rpe.cpp
        src/8080/instructions/tests/rpo.cpp
        src/8080/instructions/tests/rrc.cpp
        src/8080/instructions/tests/rst.cpp
        src/8080/instructions/tests/rz.cpp
        src/8080/instructions/tests/sbb.cpp
        src/8080/instructions/tests/sbi.cpp
        src/8080/instructions/tests/shld.cpp
        src/8080/instructions/tests/sphl.cpp
        src/8080/instructions/tests/sta.cpp
        src/8080/instructions/tests/stax.cpp
        src/8080/instructions/tests/stc.cpp
        src/8080/instructions/tests/sub.cpp
        src/8080/instructions/tests/sui.cpp
        src/8080/instructions/tests/xchg.cpp
        src/8080/instructions/tests/xra.cpp
        src/8080/instructions/tests/xri.cpp
        src/8080/instructions/tests/xthl.cpp
        src/8080/tests/emulator_memory_tests.cpp
        src/crosscutting/byte_util.cpp
        src/crosscutting/file_util.cpp
        src/crosscutting/invalid_program_arguments_exception.cpp
        src/crosscutting/string_util.cpp
        src/crosscutting/unrecognized_opcode_exception.cpp
        )

set(TEST_SOURCES_8080_H
        src/8080/cpu.h
        src/8080/emulator_memory.h
        src/8080/flags.h
        src/8080/next_byte.h
        src/8080/next_word.h
        src/8080/instructions/instructions.h
        src/crosscutting/byte_util.h
        src/crosscutting/file_util.h
        src/crosscutting/invalid_program_arguments_exception.h
        src/crosscutting/string_util.h
        src/crosscutting/unrecognized_opcode_exception.h
        )
