set(SOURCES_Z80_CPP
        src/z80/applications/cpm/cpm_application.cpp
        src/z80/applications/cpm/cpm_application_session.cpp
        src/z80/cpu.cpp
        src/z80/debug_container.cpp
        src/z80/disassemblerZ80.cpp
        src/z80/emulator_memory.cpp
        src/z80/flags.cpp
        src/z80/frontend.cpp
        src/z80/instructions/aci.cpp
        src/z80/instructions/adc.cpp
        src/z80/instructions/add.cpp
        src/z80/instructions/adi.cpp
        src/z80/instructions/ana.cpp
        src/z80/instructions/ani.cpp
        src/z80/instructions/call.cpp
        src/z80/instructions/cc.cpp
        src/z80/instructions/cm.cpp
        src/z80/instructions/cma.cpp
        src/z80/instructions/cmc.cpp
        src/z80/instructions/cmp.cpp
        src/z80/instructions/cnc.cpp
        src/z80/instructions/cnz.cpp
        src/z80/instructions/cp.cpp
        src/z80/instructions/cpe.cpp
        src/z80/instructions/cpi.cpp
        src/z80/instructions/cpo.cpp
        src/z80/instructions/cz.cpp
        src/z80/instructions/daa.cpp
        src/z80/instructions/dad.cpp
        src/z80/instructions/dcr.cpp
        src/z80/instructions/dcx.cpp
        src/z80/instructions/di.cpp
        src/z80/instructions/ei.cpp
        src/z80/instructions/hlt.cpp
        src/z80/instructions/in.cpp
        src/z80/instructions/inr.cpp
        src/z80/instructions/instruction_util.cpp
        src/z80/instructions/inx.cpp
        src/z80/instructions/jc.cpp
        src/z80/instructions/jm.cpp
        src/z80/instructions/jmp.cpp
        src/z80/instructions/jnc.cpp
        src/z80/instructions/jnz.cpp
        src/z80/instructions/jp.cpp
        src/z80/instructions/jpe.cpp
        src/z80/instructions/jpo.cpp
        src/z80/instructions/jz.cpp
        src/z80/instructions/lda.cpp
        src/z80/instructions/ldax.cpp
        src/z80/instructions/lhld.cpp
        src/z80/instructions/lxi.cpp
        src/z80/instructions/mov.cpp
        src/z80/instructions/mvi.cpp
        src/z80/instructions/nop.cpp
        src/z80/instructions/ora.cpp
        src/z80/instructions/ori.cpp
        src/z80/instructions/out.cpp
        src/z80/instructions/pchl.cpp
        src/z80/instructions/pop.cpp
        src/z80/instructions/push.cpp
        src/z80/instructions/ral.cpp
        src/z80/instructions/rar.cpp
        src/z80/instructions/rc.cpp
        src/z80/instructions/ret.cpp
        src/z80/instructions/rlc.cpp
        src/z80/instructions/rm.cpp
        src/z80/instructions/rnc.cpp
        src/z80/instructions/rnz.cpp
        src/z80/instructions/rp.cpp
        src/z80/instructions/rpe.cpp
        src/z80/instructions/rpo.cpp
        src/z80/instructions/rrc.cpp
        src/z80/instructions/rst.cpp
        src/z80/instructions/rz.cpp
        src/z80/instructions/sbb.cpp
        src/z80/instructions/sbi.cpp
        src/z80/instructions/shld.cpp
        src/z80/instructions/sphl.cpp
        src/z80/instructions/sta.cpp
        src/z80/instructions/stax.cpp
        src/z80/instructions/stc.cpp
        src/z80/instructions/sub.cpp
        src/z80/instructions/sui.cpp
        src/z80/instructions/unused.cpp
        src/z80/instructions/xchg.cpp
        src/z80/instructions/xra.cpp
        src/z80/instructions/xri.cpp
        src/z80/instructions/xthl.cpp
        )

set(SOURCES_Z80_H
        src/z80/applications/cpm/cpm_application.h
        src/z80/applications/cpm/cpm_application_session.h
        src/z80/applications/pacman/settings.h
        src/z80/cpu.h
        src/z80/debug_container.h
        src/z80/disassemblerZ80.h
        src/z80/emulator_memory.h
        src/z80/flags.h
        src/z80/frontend.h
        src/z80/next_byte.h
        src/z80/next_word.h
        src/z80/run_status.h
        src/z80/instructions/instruction_util.h
        src/z80/instructions/instructions.h
        src/z80/interfaces/emulatorZ80.h
        src/z80/interfaces/gui_observer.h
        src/z80/interfaces/in_observer.h
        src/z80/interfaces/out_observer.h
        src/z80/interfaces/session.h
        )
