set(SOURCES_Z80_CPP
        src/z80/applications/cpm/cpm_application.cpp
        src/z80/applications/cpm/cpm_application_session.cpp
        src/z80/cpu.cpp
        src/z80/debug_container.cpp
        src/z80/disassemblerZ80.cpp
        src/z80/emulator_memory.cpp
        src/z80/flags.cpp
        src/z80/frontend.cpp
        src/z80/instructions/adc.cpp
        src/z80/instructions/add.cpp
        src/z80/instructions/and.cpp
        src/z80/instructions/call.cpp
        src/z80/instructions/ccf.cpp
        src/z80/instructions/cp.cpp
        src/z80/instructions/cpl.cpp
        src/z80/instructions/daa.cpp
        src/z80/instructions/dec.cpp
        src/z80/instructions/di.cpp
        src/z80/instructions/djnz.cpp
        src/z80/instructions/ei.cpp
        src/z80/instructions/ex.cpp
        src/z80/instructions/exx.cpp
        src/z80/instructions/halt.cpp
        src/z80/instructions/in.cpp
        src/z80/instructions/inc.cpp
        src/z80/instructions/instruction_util.cpp
        src/z80/instructions/jp.cpp
        src/z80/instructions/jr.cpp
        src/z80/instructions/ld.cpp
        src/z80/instructions/nop.cpp
        src/z80/instructions/or.cpp
        src/z80/instructions/out.cpp
        src/z80/instructions/pop.cpp
        src/z80/instructions/push.cpp
        src/z80/instructions/ret.cpp
        src/z80/instructions/rl.cpp
        src/z80/instructions/rlc.cpp
        src/z80/instructions/rr.cpp
        src/z80/instructions/rrc.cpp
        src/z80/instructions/rst.cpp
        src/z80/instructions/sbc.cpp
        src/z80/instructions/scf.cpp
        src/z80/instructions/sub.cpp
        src/z80/instructions/unused.cpp
        src/z80/instructions/xor.cpp
        )

set(SOURCES_Z80_H
        src/z80/applications/cpm/cpm_application.h
        src/z80/applications/cpm/cpm_application_session.h
        src/z80/applications/pacman/settings.h
        src/z80/cpu.h
        src/z80/debug_container.h
        src/z80/disassemblerZ80.h
        src/z80/emulator_memory.h
        src/z80/flags.h
        src/z80/frontend.h
        src/z80/run_status.h
        src/z80/instructions/instruction_util.h
        src/z80/instructions/instructions.h
        src/z80/interfaces/emulatorZ80.h
        src/z80/interfaces/gui_observer.h
        src/z80/interfaces/in_observer.h
        src/z80/interfaces/out_observer.h
        src/z80/interfaces/session.h
        )
