#ifndef MIKA_EMULATORS_APPLICATIONS_LMC_APPLICATION_TERMINAL_INPUT_STATE_H
#define MIKA_EMULATORS_APPLICATIONS_LMC_APPLICATION_TERMINAL_INPUT_STATE_H

namespace emu::applications::lmc {

    enum TerminalInputState {
        NOT_AWAITING_INPUT,
        AWAITING_INPUT,
    };
}

#endif //MIKA_EMULATORS_APPLICATIONS_LMC_APPLICATION_TERMINAL_INPUT_STATE_H
